### ISSUE TITLE
Does the iframe still communicate back to parent if iframe content changes?

### ISSUE THREAD

**Issue by joetidee** [ryanseddon/react-frame-component#100]
I would like my React application to undertake the following:
1) generate a page containing an iframe,
2) load a form inside the iframe,
3) submit the form that is inside the iframe to a 3rd party service,
4) allow the 3rd party service to return a form that asks the user to supply some information,
5) once user has filled out the form and submitted it to the 3rd party, the 3rd party will send back something that tells the parent of the iframe to redirect to another page.

Is this possible with this library? The main aim to my question is whether, once the iframe navigates to a 3rd party site, will the subsequent page that is part of my site still be able to communicate with the parent page.

**Comment by ryanseddon** [comment]
If you executing within the context of the iframe and it's the same domain you can just do `window.parent.location.href = 'new url';`
