### ISSUE TITLE
How to access the iframe document to submit a form?

### ISSUE THREAD

**Issue by joetidee** [ryanseddon/react-frame-component#101]
In your documentation titled "Accessing the iframe's window and document", does the constructor that you showed in your example belong in the parent component, or the component that is loaded into the iframe?

**Comment by ryanseddon** [comment]
Currently it's on the context of the component.

```jsx
const Form = (props, context) => {
  const { document } = context;  

  // document is now a reference to the iframe document
};
Form.contextType = {
  document: PropTypes.any
};

<Frame>
  <Form />
</Frame>
```

**Comment by joetidee** [comment]
So, where does `iframeDocument` and `iframeWindow` come from ?

**Comment by joetidee** [comment]
Just to confirm then, if I wanted to load a form into an iframe and have that form automatically submit when the frame is loaded, would this work?

```
const Form = () => (
  <form action="...">
      ...
  </form>
);

class SomeComponent extends React.Component {
  constructor() {
    super();
    this.submitForm = this.submitForm.bind(this);
  }

  submitForm() {
    this.form.submit();
  }

  render() {
    return (
      <Frame contentDidMount={this.submitForm}>
        <Form ref={(form) => this.form = form }>
          ...
        </Form>
      </Frame>
    )
  }
}
```

**Comment by ryanseddon** [comment]
Yep that should work see this [demo](https://codesandbox.io/s/3xoyr0m73m)
