### ISSUE TITLE
React.findDOMNode on React 0.13.1

### ISSUE THREAD

**Issue by raeldc** [ryanseddon/react-frame-component#11]
Hi Ryan,

Recent changes in React may have affected the awesomeness of your simple component. Components that are rendered inside the Frame can't use React.findDOMNode inside componentDidMount. If you use it, there will be this error.

`Invariant Violation: findComponentRoot(..., .0.0): Unable to find element`

Here's a quick JSFiddle to show what I mean. 

https://jsfiddle.net/raeldc/3gLunvyr/3/

Try uncommenting line 42 and Re-run.

For sure this is a result of some changes in React since 0.13.0 (haven't tried 0.12.x but your examples seem to work perfectly on 0.10.x). I haven't investigate yet why this is happening exactly, I just wanna give a heads up for those who might also encounter this issue.

Cheers!

**Comment by raeldc** [comment]
I just figured out how to avoid this problem. Made a PR that fixes it. 

https://github.com/ryanseddon/react-frame-component/pull/12

And here's where you can test it.

https://jsfiddle.net/raeldc/3gLunvyr/4/

**Comment by ryanseddon** [comment]
Merged and published to npm, thanks again @raeldc
