### ISSUE TITLE
Firefox not rendering content in nested iframe components

### ISSUE THREAD

**Issue by dominiczaq** [ryanseddon/react-frame-component#110]
Hello,

Firefox is not rendering content in nested frame components.

I've created codesandbox which shows the issue: https://codesandbox.io/s/v8y6yov767

Any help would be much appreciated.

**Comment by dominiczaq** [comment]
I've found really hacky solution to make it work in Firefox, but it includes forceUpdate in render method. 

https://codesandbox.io/s/50w4v0mnvp

Not really sure how this could be implemented directly into react-frame-component.

What is strange, If you look into console.logs, render function in FrameTwo is called, but react-frame-component is never mounted.
This behaviour in FF might be connected with 3yo bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1229707

**Comment by ryanseddon** [comment]
> we don't have a special-case for firing onload manually in the no-src case

That got me thinking that if we set a src on the second iframe in theory we could avoid this bug and since we overwrite the contents when we render we could get away with it.

So I tried adding the `srcDoc` attribute and firefox rendered correctly!

```jsx
function App() {
  return (
    <Frame id="first">
      <Frame id="second" srcDoc="">
        <div>Not rendering in Firefox</div>
      </Frame>
    </Frame>
  );
}
```

https://codesandbox.io/s/8kkx1m6j8
