### ISSUE TITLE
Warning in console (React 16.4.0)

### ISSUE THREAD

**Issue by WizOzHeir** [ryanseddon/react-frame-component#111]
<img width="570" alt="screen shot 2018-06-19 at 20 05 20" src="https://user-images.githubusercontent.com/11841201/41612630-27e359be-73fc-11e8-8c95-e43b15dafffb.png">

I can fix this warning. May I have a commit access ?

**Comment by StephenHaney** [comment]
It looks like this commit made some key changes:
https://github.com/ryanseddon/react-frame-component/commit/529a9f8a45d10b30e88371d8bf9b0b30947a6a3a

The head prop now renders inside the <head></head> of the iframe. Note the readme file still says – incorrectly – that the head prop attaches into the body of the iframe .

The previous pattern was to pass a div to the head prop, then attach new scripts and styles to the div reference.

If you follow this pattern now, you'll insert a div inside the <head> of the frame, which isn't semantic HTML and will throw the error @Viscontes posted.
