### ISSUE TITLE
css is not getting loaded.

### ISSUE THREAD

**Issue by sugirDefi** [ryanseddon/react-frame-component#114]

**Comment by Kosai106** [comment]
You need to provide more details than this.

**Comment by DocCaliban** [comment]
I was playing around with this and I think I know what he means.  So Details follow:

Repro:
I have a component like so

Component
```
import React from 'react';
import './FeatureCard.css';

const FeatureCard = ({ image, body, cta }) => {
  return (
    <div className="feature-card flex-vertical">
      <div className="feature-card-top flex-center">
        <div className="feature-card-header">{image}</div>
        <div className="feature-card-body">{body}</div>
      </div>
      <div className="feature-card-cta">{cta}</div>
    </div>
  );
};
export default FeatureCard;
```
CSS
```
.feature-card {
  border-radius: 4px;
  box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.18);
  width: 350px;
  margin: 1em;
  height: 400px;
  background-color: #fafafa;
  padding: 1em;
}
```
Frame
```
<Frame>
    <FeatureCard />
</Frame>
```

What I expect to get in this instance is a nicely styled component in the frame.
What I actually get is just a bunch of plain HTML.

I think the key is that when using inline styles or CSS modules, it likely works fine (I haven't tested this),
But, when relying on an external stylesheet it's not working.  

This likely affects any global CSS as well.

**Comment by deshiknaves** [comment]
You could do something like this:

```javascript
const getStyles = () => {
  let head = '';
  const newLink = document.createElement('link');
  newLink.rel = 'stylesheet';
  newLink.href = 'foo';
  document.head.appendChild(newLink);

  const sheets = Array.from(document.querySelectorAll('link[rel=stylesheet]'));
  const styles = Array.from(document.querySelectorAll('head style'));

  sheets.forEach(link => {
    head += link.outerHTML;
  });

  styles.forEach(style => {
    head += style.outerHTML;
  });

  return head;
};
```

```javascript
<Frame
  contentDidMount={this.onLoad}
  initialContent={`<!DOCTYPE html><html><head>${getStyles()}</head><body><div class="frame-root"></div></body></html>`}
>
    <p>Something</p>
</Frame>
```

**Comment by shaktech786** [comment]
I was having the same problem, but I tried the above method and it kind of worked? I got the main styling but it did not render the inline styling inside the component i'm trying to wrap with a <Frame>. Any ideas?

**Comment by boydc2014** [comment]
having the same problem here, solved with the above approach. But this looks like the parent\children's css are putting together, which is against the reason why I want use IFrame first to gain stylesheet isolation. 

is there some recommended way, to make the stylesheet totally coupled @deshiknaves

**Comment by ryanseddon** [comment]
If you want to couple styling with a component then you'd need to use a css-in-js library like styled-components. That way you can tell the styles generated by styled-components to inject into an iframe.

**Comment by ripley** [comment]
> If you want to couple styling with a component then you'd need to use a css-in-js library like styled-components. That way you can tell the styles generated by styled-components to inject into an iframe.

Will this put extra limitation when users want to add third party components to the iframe, like https://design-system.pluralsight.com/components/tab ? It looks to me this will narrow the scenarios for this component.
