### ISSUE TITLE
Can't load Google Recaptcha

### ISSUE THREAD

**Issue by subhannn** [ryanseddon/react-frame-component#116]
Hello, 

I have trouble with frame component, when i will show google recaptcha with this plugin "react-google-recaptcha" that cant working, because google script insert in outside iframe. So that script callback cant working.

```javascript
import Frame from 'react-frame-component';
import ReCAPTCHA from "react-google-recaptcha";

<Frame>
       <ReCAPTCHA sitekey="API_KEY"  />
</Frame>
```

**Comment by ryanseddon** [comment]
Seems to render fine inside the iframe? https://codesandbox.io/s/m5ovx9w1zj

**Comment by ryanseddon** [comment]
Ok I see that it injects the script into the parent, you might want to follow up on this issue https://github.com/dozoisch/react-google-recaptcha/issues/65

**Comment by ryanseddon** [comment]
Closing since this is an issue with recaptcha and it's dependencies itself
