### ISSUE TITLE
Is there a need for a child in the iframe body?

### ISSUE THREAD

**Issue by joetidee** [ryanseddon/react-frame-component#119]
We are using the <Frame> component to auto-submit a form to a url. This url then returns a redirection response back to the iframe. We have had this error appear in the browser console on rare occasions:

> Uncaught TypeError: Cannot read property 'children' of null

This seems to suggest that it is trying to find a child node of the `body`, as per line 66 of Frame.jsx.

We are thinking that it may be because it the redirection response (mentioned above) that we send  back to the iframe does not include any child div in the `body`:
```

res.writeHeader(200, { 'Content-Type': 'text/html' });
    res.write(`
        <head>
        <script>
            ...
        </script>
        </head>
        <body/>
    `);
    res.end();
```

Could this be a likely reason for this error? If so, do we need to mimic the div used by `initialContent`?

`<div class="frame-root"></div>`

In addition to this, is it reasonable to assume that any parent of a `<Frame>` component can re-render and the contents of the iframe be unaffected by the re-rendering of `<Frame>`?

**Comment by ryanseddon** [comment]
React will warn when rendering directly to the body of a document so we need to have at least 1 child in body for this to not throw.

https://github.com/ryanseddon/react-frame-component/blob/847efc6a095b44c0f09c7314521e715436871448/src/Frame.jsx#L66

**Comment by ryanseddon** [comment]
> In addition to this, is it reasonable to assume that any parent of a <Frame> component can re-render and the contents of the iframe be unaffected by the re-rendering of <Frame>?

No the frame will not re-render if the parent re-renders
