### ISSUE TITLE
How to load right css chunk in iframe?

### ISSUE THREAD

**Issue by IvanKalinin** [ryanseddon/react-frame-component#122]
Hi there.

I have an app that loads components in multiple iframes.
So I have a structure kind of like 
```
  <Frame initialContent={"<!DOCTYPE html><html><head><link href="`urlToBuild`" rel="stylesheet"></head><body><div></div></body></html>`}>
    <Container1></Container1>
  </Frame>

  <Frame initialContent={"<!DOCTYPE html><html><head><link href="`urlToBuild`" rel="stylesheet"></head><body><div></div></body></html>`}>
    <Container2></Container2>
  </Frame>

  <Frame initialContent={"<!DOCTYPE html><html><head><link href="`urlToBuild`" rel="stylesheet"></head><body><div></div></body></html>`}>
    <Container3></Container3>
  </Frame>
```

Also I use webpack 4 and mini-css-extract-plugin.

For containers I am going to use dynamic import. 
It will split not the only js code but css bundle as well.

How can I load right css chunk in right iframe?

**Comment by ryanseddon** [comment]
It's a little vague how your loading your CSS in dev dynamic import in place of the `urlToBuild` string?

This is beyond support for this component you'd be better off asking a webpack question on stackoverflow.
