### ISSUE TITLE
Export full context instance

### ISSUE THREAD

**Issue by berdyshev** [ryanseddon/react-frame-component#126]
In #104 the new official context API was implemented, but since react 16.6.0 a component can subscribe to the context using the static property [`contextType`](https://reactjs.org/docs/context.html#classcontexttype) which requires the full context instance created by `React.createContext()`.

So the solution is to export from the package not only consumer but the full context instance too.

**Comment by dominiczaq** [comment]
I believe this would require major version bump as react-frame-component currently specifies `"react": ">= 16.3",` as [peerDependency](https://github.com/ryanseddon/react-frame-component/blob/2cf30f1c76e609d32d57a7fc80faf1fa69dd3623/package.json#L93)

**Comment by berdyshev** [comment]
I don't think so, because it doesn't affect the library and it's dependencies, since nothing should be implemented but the changes to the export.

**Comment by dominiczaq** [comment]
After consideration I believe you're right @berdyshev. I've added PR with suggested export.

**Comment by ryanseddon** [comment]
This has been merged.
