### ISSUE TITLE
Shadowing window globals

### ISSUE THREAD

**Issue by bradbarrow** [ryanseddon/react-frame-component#132]
This is similar to #40 I believe.

I'm trying to render an app that uses `react-pose` into a `Frame`. (actually, I'm using [playroom](https://github.com/seek-oss/playroom) which does this) but it's not able to work with it's refs properly.

It's got a number of `instanceof` checks like this:

https://github.com/Popmotion/popmotion/blob/master/packages/react-pose/src/components/PoseElement/index.tsx#L169

Basically, `if ref instanceof Element`.

In the case where this is rendered in the Frame though, the `Element` on `ref`'s proto chain is the iFrame DOM Element, whereas `Element` in the condition is our browsers `window.Element`. 

Naively, I wonder if there's a way to shadow the `window` globals with the `iframe.contentWindow` globals...or some sort of bind? (iframe n00b here).

Thanks for the hard work on this :)

More context:

https://github.com/seek-oss/playroom/issues/45

**Comment by ryanseddon** [comment]
Closing since this is a react-pose issue
