### ISSUE TITLE
How to insert html sting to iframe?

### ISSUE THREAD

**Issue by Tsyklop** [ryanseddon/react-frame-component#134]
I have a next code:

```
<Frame className="site-iframe" frameBorder="0">
      {this.props.iframeContent?this.props.iframeContent:<h1>Loading...</h1>}
</Frame>
```
`iframeContent` - is loaded from server. Server returning full html text starts with `<!DOCTYPE HTML>` and ends with </html>. But `Frame` show this text like plain text, not a html tree.

How i can insert html?

**Comment by dominiczaq** [comment]
Afaik Frame component already adds HEAD for the iframe so you should omit it in your response. 
Additionally I think it's connected with dangerousylySetInnerHTML not with the <Frame /> component itself. https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

**Comment by dominiczaq** [comment]
Maybe you could also use something like https://www.npmjs.com/package/html-react-parser

**Comment by Tsyklop** [comment]
@dominiczaq I already tried use `html-react-parser`, but i get many error from react.

**Comment by dominiczaq** [comment]
What errors? Try with dangerouslyInnerHTML without html-react-parser.

https://codesandbox.io/s/2xl99wj03y

This works perfectly fine but I would advise against directly rendering
content from server without any whitelisting, especially if some of the
data is provided by the user.

**Comment by Tsyklop** [comment]
@dominiczaq errors like `in table element need use tbody`, `need use className but not class` e.t.c
Thanks, for your response.

**Comment by dominiczaq** [comment]
You're welcome, cheers!
