### ISSUE TITLE
Question: best way to render HTML that changes

### ISSUE THREAD

**Issue by samazadi** [ryanseddon/react-frame-component#135]
I have an HTML string that is being changed as the user edits their code. I want to render this code using the iframe to users. Whats the best way to update the source code of the iframe?

**Comment by dominiczaq** [comment]
Hey, I've made naive implementation for you https://codesandbox.io/s/929vp27z1p

Please not this is really not production ready - I would suggest looking into something like https://www.npmjs.com/package/html-react-parser to parse html string. Please also be very cautious when rendering user provided content as it's potential vulnerability - not so much when you're rendering only for the current user, but if it's stored somewhere on the server without proper tags whitelisting and rendered for other users I would make sure that it's properly sanitized.

**Comment by samazadi** [comment]
Brilliant! Thank you so much!
In terms of vulnerabilities, you mean something like XSS? My use case is creating an online editor similar to JSFiddle, where I render the users code in real time. I know JSfiddle has their iframe on another domain, so CORS blocks any XSS... Is there any way I can achieve something similar? What do you think would be a good solution to securing the code entered?

**Comment by dominiczaq** [comment]
Tbh I'm not sure. I think Embedding iframe inside another named iframe
might help as it would sandbox the code from reading i.e. from
localstorage. That would require some google-fu :)
