### ISSUE TITLE
Question: best way to execute javascript in the iframe

### ISSUE THREAD

**Issue by samazadi** [ryanseddon/react-frame-component#136]
I'd like to be able to execute some javascript in the iframe. Whats the best way to accomplish this?

**Comment by dominiczaq** [comment]
Hi. Try rendering a script tag inside <Frame /> component. You can add src
with desired scripts.

**Comment by samazadi** [comment]
Thanks for the reply! My issue was that I was storing users JavaScript as a string, then using the iframe to render their code. I just needed to use the eval() function to have the script run the string as js. Thanks again.

**Comment by ryanseddon** [comment]
Closing since you've figured out your problem.
