### ISSUE TITLE
Can Frame for onScroll?

### ISSUE THREAD

**Issue by volkandkaya** [ryanseddon/react-frame-component#138]
I have tried adding onScroll to <Frame> doens't seem to fire.

**Comment by dominiczaq** [comment]
could you please elaborate?

**Comment by volkandkaya** [comment]
@dominiczaq I have added onScroll to the Frame element, however when I scroll it does not fire.

Put together https://codesandbox.io/s/40om7v05w?fontsize=14, as you can see if you scroll the div it works fine, however the Frame doesn't fire.

**Comment by volkandkaya** [comment]
Was able to use FrameContextConsumer, just added document.addEventListener('scroll', handleScroll) inside it
