### ISSUE TITLE
how to connect react logic in time to wrappe component in iframe 

### ISSUE THREAD

**Issue by Vahe9611** [ryanseddon/react-frame-component#139]
I create a high order component witch wrappe  react component in Frame and i want connect my javascript code in iframe

**Comment by Vahe9611** [comment]
import React from 'react';
import Frame from 'react-frame-component';
const getStyles = () => {
    let head = '';
    const sheets = Array.from(document.querySelectorAll('link[rel=stylesheet]'));
    const styles = Array.from(document.querySelectorAll('head style'));
  
    sheets.forEach(link => {
        head += link.outerHTML;
    });
  
    styles.forEach(style => {
        head += style.outerHTML;
    });
  
    return head;
};

export default function Wrapper(WrappedComponent) {
    return class extends React.Component {
        render() {
            return this.props.viewMode === 'phone' || this.props.viewMode === 'tablet'  ? (
                <Frame
                    contentDidMount={this.onLoad}
                    initialContent={`<!DOCTYPE html><html><head>${ getStyles() } </head><body><div class="frame-root"></div></body></html>`}    
                >
                    <WrappedComponent {...this.props}/>
                </Frame>
            ) : (
                <WrappedComponent {...this.props}/>
            )
        }
    }
}

**Comment by ryanseddon** [comment]
Can you create a codesandbox.io your formatting makes it really hard to know what you're trying to do
