### ISSUE TITLE
Use of the head prop

### ISSUE THREAD

**Issue by martijnvermaat** [ryanseddon/react-frame-component#14]
I'm a bit confused about how `this.props.head` is used.

1. In `render`, it is passed directly as a `head` prop to `<iframe />`. I'm not a React expert, but if I understand correctly this means it is discarded.

2. In `renderFrameContents`, it is used as the first child of the IFrame document `<body />`. I think it would make more sense to properly render it as `<head />` in the IFrame document, probably with something like `React.render(this.props.head, doc.head);`.

Do I misunderstand?

Also, which element should `this.props.head` be? Something that can be a child of `<head />` or just `<head />` itself?

**Comment by ryanseddon** [comment]
Think of the head prop a pseudo `<head />` element where you place stuff that needs to come before the iframes main content.

I go over why we can't do this in the [article](https://developer.zendesk.com/blog/2014/05/13/rendering-to-iframes-in-react/#what-about-css-in-the-iframe) about this component, unfortunately it throws an error in IE9. Until react drops IE9 support I'll continue to do it this way.
