### ISSUE TITLE
using with react-dnd to drop elements from the parent window

### ISSUE THREAD

**Issue by zivni** [ryanseddon/react-frame-component#140]
The [example of how to use react-dnd with a frame](http://react-dnd.github.io/react-dnd/docs/api/dnd-provider) shows how to use react-frame-component  when both the drag source and drag target are both in the iframe. 

Is it possible that the drag source will be on the parent window and be dropped into an element in the iframe (in that example, that the `Box` components  will be placed in the same div as the `Example` component)  ?

**Comment by ryanseddon** [comment]
Have you tried doing this with react-dnd? Can you make a codesandbox.io with it so we can work from that.

**Comment by zivni** [comment]
Here is an example https://codesandbox.io/embed/react-dnd-example-4-kjunx I modifyed from the original react-dnd example.

Drag one of the outside boxes to the regular drag zone (below) and it works, then drag it to the frame drop zone (at the top) and it doesn't work.

**Comment by dominiczaq** [comment]
hey @zivni - I believe this is a limitation of react-dnd: https://github.com/react-dnd/react-dnd/issues/1496

**Comment by zivni** [comment]
Thanks. Closing this.
