### ISSUE TITLE
document.write is deprecated in Chrome

### ISSUE THREAD

**Issue by dakiesse** [ryanseddon/react-frame-component#144]
Last 2 month I am seeing the notice in Google Chrome console

> [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write

Will the issue be resolved?

**Comment by dominiczaq** [comment]
I'm not sure if that's only for 2 months - I think it could be much longer
:)

I'm not really sure if there is any alternative which provides same
behaviour.

**Comment by ryanseddon** [comment]
I've released an [alpha](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.0.0-alpha.0) that uses `srcdoc` to see if this could be a viable path forward.
