### ISSUE TITLE
html and body reference

### ISSUE THREAD

**Issue by IshayMaya** [ryanseddon/react-frame-component#145]
Im trying to use this lib to present my app in accessebility mode at the third bottom of the screen.
What im trying to do is to render the app inside the frame , but i have a lot of styling and calculations in the nested components that refers to the window and the body of the app.

i tried using the FameContextConsumer but it still gives me only the global body and fixed elements are reffering to the html file and not the frame.

is this a normal behavior ? maybe im not using it right ? 

`
export default function App () {
  
    const getStyles =  () =>  {
        let head = '';
        const sheets = Array.from(document.querySelectorAll('link[rel=stylesheet]'));
        const styles = Array.from(document.querySelectorAll('head style'));
      
        sheets.forEach(link => {
          head += link.outerHTML;
        });
      
        styles.forEach(style => {
          head += style.outerHTML;
        });
      
        return head;
      };

    return (
        <Frame width='100%' height='400px'
        initialContent={`<!DOCTYPE html>
        <html lang="he" dir="RTL">
        <head>
            ${getStyles()}
        </head>
        <body >
        <main></main>
       
        </body>
        </html>
        `}
      >
    <FrameContextConsumer>
    {
      ({document, window}) => {
          console.log(document.body);
          
        // Render Children
        return   <Wrapper>
                    <Router />
                </Wrapper>
      }
    }
   </FrameContextConsumer>
   </Frame>
  
    );
};
`

**Comment by dominiczaq** [comment]
By the looks of it getStyles() should work properly - is that true?

You can access your global window and document normally but when using FrameContextConsumer you should be able to access iframe's window and document.

So if you need to modify i.e. iframe's styles from within one of your deep nested components, you can do it there using <FrameContextConsumer>

**Comment by JasonTheAdams** [comment]
@IshayMaya Clever idea grabbing the styles and such from the main document and placing them in the iframe. I ended up using that and it worked great. Thank you!

**Comment by ryanseddon** [comment]
Seems this is solved? Closing.
