### ISSUE TITLE
Iframe cross-origin form submittion

### ISSUE THREAD

**Issue by dane-brown** [ryanseddon/react-frame-component#157]
I currently have a `<Frame />` that submits a form to an external payment gateway.

This works perfectly in browsers such as Chrome/Firefox but when it comes to Internet Explorer or Edge I get `Access is Denied` error when the form posts to the external URL.

After getting this `Access is Denied` error I am unable to interact with anything outside of the iframe.

Any assistance will be greatly appreciated

**Comment by ryanseddon** [comment]
Are you able to recreate the issue without using the external payment gateway? Hard to help without a test case to look at.

**Comment by thomaswelton** [comment]
Same issue here, using the frame component to submit a form to Worldpay.
Once the form in the frame is submitted I'm assuming react frame component is trying to read or update the content of the iframe in a render causing the `Access is Denied` error.
Wrapping the Frame in an Error Boundary allows this issue to be suppressed and for communication via post message to continue

**Comment by ryanseddon** [comment]
Here's a [test case](https://codesandbox.io/s/wild-frost-fub1i?file=/src/App.js) that posts to a cross origin [testing service](https://ptsv2.com/) does this present the issue in edge? If so what version?

**Comment by ryanseddon** [comment]
I tried my test case in edge 89 and it worked fine I don't have access to IE11, IE11 is also been dropped in the latest major release of this component.

**Comment by ryanseddon** [comment]
Closing due to not being able to reproduce. If you can show a test case that can reproduce the issue happy to re-open and investigate.
