### ISSUE TITLE
Upgrade to use React.createRef()

### ISSUE THREAD

**Issue by joetidee** [ryanseddon/react-frame-component#158]
When running tests, we are getting:

`TypeError: Cannot read property 'addEventListener' of null`

which refers to this block in Frame.jsx:

```
componentDidMount() {
    this._isMounted = true;

    const doc = this.getDoc();
    if (doc && doc.readyState === 'complete') {
      this.forceUpdate();
    } else {
      this.node.addEventListener('load', this.handleLoad);
    }
  }
```

and suggests that `node` is null. We are using React >16.3, in which refs were changed to use `React.createRef()` - could this be the issue(?)

This started occurring after upgrading from v2.0.2 to v4.1.1 of `react-frame-component`.

**Comment by ryanseddon** [comment]
Potentially, wanna do a PR to bump this to the latest react release?

**Comment by walaszczykm** [comment]
Hi @ryanseddon 👋  I tried to address it in https://github.com/ryanseddon/react-frame-component/pull/189 if you don't mind 🙂
