### ISSUE TITLE
Trying to render plyr player inside frame

### ISSUE THREAD

**Issue by NykolaySavin** [ryanseddon/react-frame-component#160]
I have very basic code for frame render:
`<Frame><Player /></Frame>` 
And very basic code for player:

https://codepen.io/savin171099/pen/WNQjoMp

Player is working good without frame, but it is not rendering inside frame. Any thoughts?

**Comment by ButlerBorst** [comment]
Having the same problem

**Comment by fxnoob** [comment]
@NykolaySavin @ButlerBorst   plyr player doesn't support loading in an iframe, 
One thing you can do is to replace all the document and window objects in that lib with iframes window and document object.
To get  iframe's window and document object you can do this :-
<IFrame ref={handleRef} contentDidMount={onContentDidMount} {...props}>
      <FrameContextConsumer>
        {({ document, window }) => (
          <Div
            window={window}
          />
        )}
      </FrameContextConsumer>
    </IFrame>
e.g. first I've noticed here :
https://github.com/sampotts/plyr/blob/98dbb2e43ffc830737a1b4b4ea631482fd89bfdb/src/js/plyr.js#L56

**Comment by ryanseddon** [comment]
@NykolaySavin did @fxnoob suggestion fix it for you? Closing for now since I'm pretty sure that'll fix it.
