### ISSUE TITLE
Won't work when some extension add dom to body 😂😂😂

### ISSUE THREAD

**Issue by xiaoshuangLi** [ryanseddon/react-frame-component#162]
There is a strange issue.Some [extension](https://chrome.google.com/webstore/detail/%E6%9C%89%E9%81%93%E8%AF%8D%E5%85%B8chrome%E5%88%92%E8%AF%8D%E6%8F%92%E4%BB%B6/eopjamdnofihpioajgfdikhhbobonhbb?hl=zh-CN) may add dom when the page is created.So ```initialContent``` won't be written to right place. Please help me. 😂😂😂

I think using ```doc.body.children.length``` is not safe. Maybe ```props.initialContent``` has empty body.

```js
 /*
  *  entension may create dom before following code run
  *  so doc.body.children.length will not be 0
  **/
if (doc.body.children.length < 1) {
  doc.open('text/html', 'replace');
  doc.write(this.props.initialContent);
  doc.close();
}
```

![image](https://user-images.githubusercontent.com/12060054/81814729-b2a5e300-955b-11ea-9297-cc52951a0add.png)

**Comment by jinasonlin** [comment]
I also encountered the same problem. 😂

**Comment by pmehta18** [comment]
@xiaoshuangLi You can add following props in <StyledFrame> component
`initialContent={'<!DOCTYPE html><html><head></head><body><div class="frame-root" id="mount-target"></div></body></html>'}
mountTarget="#mount-target"`

**Comment by ryanseddon** [comment]
Can you try the [alpha release](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.0.0-alpha.0) and see if that works `react-frame-component@alpha`

**Comment by xiaoshuangLi** [comment]
> Can you try the [alpha release](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.0.0-alpha.0) and see if that works `react-frame-component@alpha`

Thanks. It works. But i can't find this commit in git repo.it would be so glad to see the code you changed.

**Comment by ryanseddon** [comment]
@xiaoshuangLi it's a published tag based off of #124

**Comment by edrpls** [comment]
@ryanseddon I just tried [v5.0.0-alpha.0](https://github.com/ryanseddon/react-frame-component/tree/v5.0.0-alpha.0) and it works fine! Thank you!

**Comment by ryanseddon** [comment]
v5 is now the [latest release](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.0.0)
