### ISSUE TITLE
Child elements instantiated twice

### ISSUE THREAD

**Issue by darbs** [ryanseddon/react-frame-component#17]
The recent commit of pull req  #16 causes the child elements to be instantiated twice. Once on the initial render and again in renderFrameContents, effectively undoing #12.

**Comment by daviferreira** [comment]
True, just bumped into this myself.

So there are a couple of ways to solve this. One is going back to the original PR idea and just pass specific props instead. The other one is use JSX with spread operators so we can do something like: `var  { children, ...other } = this.props`. And we could also use some pure javascript cloning method like Object.assign and remove the children prop.

What are your thoughts, @ryanseddon?

**Comment by ryanseddon** [comment]
We should probably just drop the children props in the initial render. Something like this:

```js
render: function() {
  delete this.props.children;
  return React.createElement('iframe', this.props);
}
```

**Comment by ryanseddon** [comment]
PRs welcome @darbs

**Comment by ryanseddon** [comment]
Eh scratch that then you'd never have any children render, suggestions welcome.
