### ISSUE TITLE
iframe's body becomes empty when frames are reordered

### ISSUE THREAD

**Issue by moroshko** [ryanseddon/react-frame-component#170]
Imagine rendering multiple `iframe`s and letting users to reorder them.

Surprisingly, when `iframe`s are reordered, the `<body>` of one of them becomes empty.

Is this a bug, or am I missing something?

```
function App() {
  const [frames, setFrames] = useState(["first", "second"]);

  return (
    <div className="app">
      <div className="framesContainer">
        {frames.map(frame => (
          <div className="frame" key={frame}>
            <Frame style={{ width: 200, height: 200 }}>
              <h1>Hello World</h1>
            </Frame>
            <div>{frame}</div>
          </div>
        ))}
      </div>
      <div className="actions">
        <button
          onClick={() => {
            setFrames(frames => [frames[1], frames[0]]);
          }}
        >
          Swap frames
        </button>
      </div>
    </div>
  );
}
```

[CodeSandbox](https://codesandbox.io/s/reordering-iframes-bug-byn4s)

**Comment by ryanseddon** [comment]
I think it's something to do with the key your using just messing around with it and this doesn't cause the second frame to flash on re-order. 

I don't get the empty body like you describe but I only looked at it in firefox.

https://codesandbox.io/s/reordering-iframes-bug-forked-fdomc?file=/src/App.js

**Comment by ryanseddon** [comment]
I could only reproduce this in safari (13.1.2) with your example. However I tried the [alpha release](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.0.0-alpha.0) and that seems to fix the problem https://codesandbox.io/s/reordering-iframes-bug-forked-sn9ie

**Comment by ryanseddon** [comment]
Alpha release is now stable [major release](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.0.0)
