### ISSUE TITLE
Strange error using vimeo

### ISSUE THREAD

**Issue by peacepostman** [ryanseddon/react-frame-component#172]
Hello,

I am facing an issue while using @vimeo/player inside react-frame-component. I can instantiate the player but nothing happen after the ready promise. I've made a demo to be as clear as possible. I may be forgetting something.

https://codesandbox.io/s/strange-bouman-erboz?fontsize=14&hidenavigation=1&theme=dark

I suggest using firefox because chrome has the autoplay policy issue using codesandbox

Best regards,

**Comment by ryanseddon** [comment]
Could be related to #160, does vimeo support loading the video iframe within another iframe?

**Comment by ryanseddon** [comment]
So I think there is a weird window context issue going on here that might require the vimeo library to allow passing in a document and window context into their `Player` class. 

A way around this issue for now is to use the `initialContent` prop to add the player, the down side of this is you'll need to teardown the iframe to change the video.

https://codesandbox.io/s/pedantic-morning-uxut6?file=/src/App.js

```jsx
<Frame
  initialContent={`<!DOCTYPE html><html><head></head><body>
  <script src="https://player.vimeo.com/api/player.js"></script>
  <div id="player"></div>
  <script>
      var options = {
          id: 59777392,
          height: 200
      };

      var vid = new Vimeo.Player("player", options);
      vid.play()
  </script>
  <div class="frame-root"></div></body></html>`}
/>
```
