### ISSUE TITLE
How to remove body margin in iFrame

### ISSUE THREAD

**Issue by eugle** [ryanseddon/react-frame-component#180]
How to remove body margin in iFrame

![image](https://user-images.githubusercontent.com/24447931/103091310-bf7cd000-462e-11eb-900a-a9af14b3e2dc.png)

**Comment by wildgeodude** [comment]
@eugle Did you find a solution in the end?

**Comment by eugle** [comment]
There is no solution

**Comment by mkadsv** [comment]
@eugle  just override it
![override_documen_body_style](https://user-images.githubusercontent.com/60241457/105389426-af73f400-5bcc-11eb-85b1-6bae0c5951fb.png)

**Comment by seleckis** [comment]
I see you are using styled-components. Crate global style for the content fo the iframe and remove margin with
```
body {
  margin: 0;
}
```
https://styled-components.com/docs/api#createglobalstyle

**Comment by ryanseddon** [comment]
You can also use the `head` prop to pass a stylesheet see [demo](https://codesandbox.io/s/vigorous-rain-nqsp7?file=/src/index.js:225-288)
