### ISSUE TITLE
while using 3rd party (libraries) Dom manupulation happens in parent DOM

### ISSUE THREAD

**Issue by rohanvachheta** [ryanseddon/react-frame-component#181]
while using react-frame-component we get document object but what if we are using 3rd party package in our codebase and that library has use document object , that document object actully refers to the parent not in iframe 
- it created issue while listening events from that 
- also sometimes css of that library don't apply directly , we've to use styled component

**Comment by Reykjavik151** [comment]
same for me

**Comment by emiralp** [comment]
same here :(

**Comment by emiralp** [comment]
I ended up using oldschool vanilla+react:

`const Iframer = (props) => {
  let iframe_ref = null

  const writeHTML = (frame) => {

    if (!frame) {
      return;
    }
    iframe_ref = frame;
    let doc = frame.contentDocument;
    let rstr = "";

    try {
      rstr = renderToString(props.content);
    } catch(e) {
      rstr = "Error #217417652";
    }

    doc.open();
    doc.write(rstr);
    doc.close();
    frame.style.width = '100%';
  }

  return (
   <iframe src="about:blank" frameBorder="0" ref={writeHTML} className={props.classes} />
  )
}`

Usage:

`<Iframer classes="wh100 editorPreview" content={
    <Preview />
} />`

**Comment by ryanseddon** [comment]
@rohanvachheta can you show me what's happening with a test case in codesandbox?

**Comment by ryanseddon** [comment]
@rohanvachheta if you use case is specifically with styled-components here's how you can tell styled components to put the css inside the `<Frame>` component: https://codesandbox.io/s/objective-dream-rrjwg?file=/src/App.js

Unfortunately if you require iframes and a library always assumes to be in the parent context then you're out of luck. You'll have to get the library authors to allow passing in the window or document context to get it to work.

**Comment by rohanvachheta** [comment]
@ryanseddon  hey, no it's not specific to styled-component, this weekend I will update you with code sandbox. I didn't get much time during weekdays to create that.

**Comment by joshgillies** [comment]
Running into this issue also, specifically when using with `react-twitter-widgets`. I've put together an example https://codesandbox.io/s/serene-haze-b5jgu with the minimal failing case. The expectation is that the Tweet should be embedded in both the parent and preview frame.

**Comment by ryanseddon** [comment]
If you inspect the `<Frame>` you can actually see the tweet is rendered in there it just seems to be not removing the styles on the iframe within the iframe so it's visually hidden.

![Screen Shot 2021-06-15 at 4 30 49 pm](https://user-images.githubusercontent.com/143402/122003962-1b166200-cdf7-11eb-9c77-0207b316326d.png)
