### ISSUE TITLE
external stylesheet not getting applied on iframe child component 

### ISSUE THREAD

**Issue by garima26jain** [ryanseddon/react-frame-component#182]
I  followed Rendering to iframe article. The explaination was pretty well . I tried implementing the same way but external stylesheet styles are not getting applied into the iframe content/child component . 
Here is the link for sandbox <https://codesandbox.io/s/crazy-sea-xzmz6>

**Comment by ryanseddon** [comment]
That's because of how you're referring to your css file in that codesandbox, if you create copy `styles.css` to the public folder than your demo will work.
