### ISSUE TITLE
Frame Fails to Load When Deployed but Works Locally

### ISSUE THREAD

**Issue by adamjberg** [ryanseddon/react-frame-component#188]
Using a `<Frame/>` worked perfectly for me in development.  However I ran into issues deploying where the iframe would fail to load.  After some debugging, I think this is because X-Frame-Options is set to SAMEORIGIN.  Unfortunately, just setting that header locally doesn't reproduce the issue.  

Here are the error logs I'm seeing in the console.

![image](https://user-images.githubusercontent.com/1812989/119418018-f45b8480-bcab-11eb-98e4-e773ea15bea9.png)

**Comment by ryanseddon** [comment]
`X-Frame-Options` is about the host page, that shouldn't effect the Frame component from rendering. 

Looking at your stack trace it seems the `getMountTarget` method inside Frame.jsx can't find any children in the frame body. 

I'll need more information and a reduced test case to help you any further.

**Comment by ryanseddon** [comment]
Closing, if it is an issue with this library then please create a test case.
