### ISSUE TITLE
React Testing Library 'Target Container is not a DOM element'

### ISSUE THREAD

**Issue by Jiglet** [ryanseddon/react-frame-component#193]
Hello, using this component helped a lot in getting a functionality working in my current project but it seems it breaks when I try to render it in react-testing-library. Even with just rendering an empty <Frame></Frame> with nothing else in the component will throw this error while testing. 
Has anyone found a workaround to this or know why it's happening?

Thanks!

**Comment by ryanseddon** [comment]
So dug into this last night and it seems react-testing-library uses jsdom which doesn't support `srcdoc` on iframes so when the component checks for children within the iframe dom it returns an empty string and throws that error.

https://github.com/jsdom/jsdom/blob/04f6c13f4a4d387c7fc979b8f62c6f68d8a0c639/lib/jsdom/living/helpers/document-base-url.js#L25

There was also [this PR](https://github.com/jsdom/jsdom/pull/2389) which added support for srcdoc but then was quickly reverted and never worked on again...

Your possible path forward here would be to change your test environment to run in an actual browser and not jsdom or mock the frame component.

**Comment by matheusslg** [comment]
In my case, I just ignore the frame component inside the setupTests.js file

```js
jest.mock('react-frame-component', () => {
  return (props) => <div>{props.children}</div>
})
```
