### ISSUE TITLE
Is there any way to mask the document and window for child components

### ISSUE THREAD

**Issue by RavenColEvol** [ryanseddon/react-frame-component#194]
I've gone through the issues which also targets the same issue which I'm referring to. 
For using react-frame-component we have to change the way of referring document and window. 

Like to use a third party package we have to change the package to make it work for react-frame-component.

I wanted a way by which we can mask the document and window for components inside Frame component.

**Comment by ryanseddon** [comment]
What exactly are you asking by `mask`? You mean somehow proxy calls of `document` and `window` to the frame context?

This is a limitation of rendering iframes programmatically, if a library assumes always being in the parent context then it'd be hard to proxy window/document calls.

There's a few workarounds:
1. Use [patch-package](https://github.com/ds300/patch-package) to create a patch file to fix the node module
2. Create a PR/issue and get it fixed upstream in the package
3. Go down a complex rabbit hole of loading you 3rd party deps inside [ses compartments](https://github.com/endojs/endo/tree/master/packages/ses) with the iframe globals as endowments
