### ISSUE TITLE
Anchors have wrong href inside frame after switching from another page

### ISSUE THREAD

**Issue by seleckis** [ryanseddon/react-frame-component#197]
**Steps to reproduce:** 
1. Open test page: https://3orql.csb.app/page
2. Click the link which points to "/page", browser would navigate to "/page".
3. Hover an anchor link "#anchor" and check where the browser is going to lead you.

**Expected result:**
Browser shows url "/page#anchor"

**Actual result:**
Browser shows url "#anchor"
If there would be another initial page, browser would show url "/initial-page#anchor" but must be "/page#anchor".

Tested with react-router, but I guess there would be the same effect when using just `history.push`.

Test page: https://3orql.csb.app/page
Sandbox: https://codesandbox.io/s/new-microservice-3orql?file=/src/App.js

**Comment by seleckis** [comment]
As a workaround (not presented in the sandbox) I have created an initial content with `<base>` tag inside `<head>` and I'm changing it's `href` attribute inside FrameContext every time the location is changing. Something like this:
```js
const { pathname } = useLocation();
useEffect(() => {
    frameContext.document.head.getElementsByTagName("base")[0].setAttribute("href", slug);
}, [pathname]);
```
I'd appreciate it, if there is a better solution or may be handled by `react-frame-component` if legit.

**Comment by ryanseddon** [comment]
I believe this is due react router assuming navigation happens on the parent document, the actual `location.href` of the iframe is `about:srcdoc` so when clicking the anchor which isn't intercepted (is that correct?) by react router it's doing the correct thing and navigating to the parent url inside the iframe which doesn't work. 

Another way to make this navigate properly is to add the `target="_parent"` to the anchor to make sure it navigates on the right window context. Or you could let react router handle it via `Link`.

I don't think this is something react frame would handle

**Comment by seleckis** [comment]
Thanks for the tip @ryanseddon. I have forgotten about `target="_parent"`, seems could be simpler solution than updating base tag inside iframe each time url changes. Seems clear html example of iframe and history.push without React has the same issue. Well, seems it is not an issue, we can call it an unsuspecting expected feature. :) I'm closing this issue.
