### ISSUE TITLE
Tests not passing under karma-firefox-launcher

### ISSUE THREAD

**Issue by zealoushacker** [ryanseddon/react-frame-component#20]
If we switch karma's browser configuration to Firefox, the tests fail.

For what it's worth, when setting the launcher to Chrome, the tests pass, just as they do with PhantomJS.

This was also true when I attempted to write my own test suite to test for rendered subcomponents inside the `<iframe>` rendered by `react-frame-component`. Of course this could just be an issue with how the browser handles iframes. The purpose of this issue is mostly to discuss it, but perhaps there's probably no use fixing it within this repo, unless we basically add `karma-firefox-launcher` as a dep, and configure karma to launch Firefox.

```
> react-frame-component@0.3.4 test /Users/alex/react-frame-component
> gulp test

[15:57:53] Using gulpfile ~/react-frame-component/gulpfile.js
[15:57:53] Starting 'build'...
[15:57:56] Finished 'build' after 3 s
[15:57:56] Starting 'test'...
[15:57:56] Starting Karma server...
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser Firefox
INFO [Firefox 39.0.0 (Mac OS X 10.10.0)]: Connected on socket edKRjh-dUgFUQQocK6ZK with id 78618126
Firefox 39.0.0 (Mac OS X 10.10.0) Frame test should create an iFrame with a <link> tag inside FAILED
    TypeError: body.querySelector(...) is null in /Users/alex/react-frame-component/test/processed/Frame_spec.js (line 21994)
    [177]</</<@/Users/alex/react-frame-component/test/processed/Frame_spec.js:21994:12

Firefox 39.0.0 (Mac OS X 10.10.0) Frame test should create an iFrame with a <script> and insert children FAILED
    TypeError: body.querySelector(...) is null in /Users/alex/react-frame-component/test/processed/Frame_spec.js (line 22008)
    [177]</</<@/Users/alex/react-frame-component/test/processed/Frame_spec.js:22008:12

Firefox 39.0.0 (Mac OS X 10.10.0) Frame test should create an iFrame with multiple <link> and <script> tags inside FAILED
    Expected 0 to equal 2.
    [177]</</<@/Users/alex/react-frame-component/test/processed/Frame_spec.js:22022:5

    Expected 0 to equal 1.
    [177]</</<@/Users/alex/react-frame-component/test/processed/Frame_spec.js:22023:5

Firefox 39.0.0 (Mac OS X 10.10.0) Frame test should encapsulate styles and not effect elements outside FAILED
    TypeError: Argument 1 of Window.getComputedStyle is not an object. in /Users/alex/react-frame-component/test/processed/Frame_spec.js (line 22039)
    [177]</</</getColour@/Users/alex/react-frame-component/test/processed/Frame_spec.js:22039:18
    [177]</</<@/Users/alex/react-frame-component/test/processed/Frame_spec.js:22043:12

Firefox 39.0.0 (Mac OS X 10.10.0): Executed 8 of 8 (4 FAILED) (0.13 secs / 0.113 secs)

/Users/alex/react-frame-component/gulpfile.js:31
      throw err;
            ^
Error in plugin 'gulp-karma'
karma exited with code 1
    at done (/Users/alex/react-frame-component/node_modules/gulp-karma/index.js:56:30)
    at ChildProcess.<anonymous> (/Users/alex/react-frame-component/node_modules/gulp-karma/index.js:82:7)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
npm ERR! Test failed.  See above for more details.
```

**Comment by zealoushacker** [comment]
Interestingly enough, in this case, the component's iframe's `readyState` is not `complete` after finding the dom node post-addition to the dom. With chrome, the `readyState` is complete.

**Comment by ryanseddon** [comment]
Hmm it should recursively call `renderFrameContents` on each event loop tick until the `readyState` is `complete` in firefox. I'll have to dig into why firefox fails the test. This definitely works in firefox i've been using this in prod for 18 months.

**Comment by zealoushacker** [comment]
#21 Should close this issue, so long as travis and saucelabs are configured when you merge. Alternatively, you might keep the `Frame_spec.js` fixes, but remove the saucelabs recommendation.

**Comment by cmmartin** [comment]
It's not just the tests. I'm experiencing this issue in Firefox 39.0.3. The iframe contents are never rendered. The readyState is set to  ```uninitialized``` and remains ```unitialized``` despite the continuous recursive checks. I'm looking into workarounds like possibly rendering the react components on the iframe's  onload event. I'll let you know if I figure it out. You might want to check on that production app @ryanseddon
