### ISSUE TITLE
Style import are not included

### ISSUE THREAD

**Issue by DerGoogler** [ryanseddon/react-frame-component#200]
These styles are getting not included
![image](https://user-images.githubusercontent.com/54764558/142876398-06b5cd35-652e-41aa-999e-014bb2500038.png)

**Comment by ryanseddon** [comment]
Can you create a test case please

**Comment by mamo-muj** [comment]
@ryanseddon I think in your blog you mentioned you can add <link> tags inside the `initialContent` prop however, that hasn't been helpful to me. At first I thought it must've been the wrong import but doesn't look like it. I think in the blog there was a `head` prop but not sure if that works?

**Comment by mamo-muj** [comment]
`<Frame initialContent='<!DOCTYPE html><html><head><link href="../src/css/main.css" /></head><body><div id="mountHere"></div></body></html>'>
  <FixedPrice brandColor={brandColor} accent1={accent1} accent2={accent2} />
</Frame>`

An example to show of what I'm trying to do

**Comment by mamo-muj** [comment]
```
<Frame initialContent='<!DOCTYPE html><html><head><link href="../src/css/main.css" /></head><body><div id="mountHere"></div></body></html>'>
  <FixedPrice brandColor={brandColor} accent1={accent1} accent2={accent2} />
</Frame>
```

An example of this

**Comment by ryanseddon** [comment]
`initialContent` is static and won't execute and scripts or styles AFAIK, what you want to do is use the `head` prop see tests:

https://github.com/ryanseddon/react-frame-component/blob/b4a0282bc1d2e0966d2764bd5d4abfb963e04490/test/Frame.spec.jsx#L68-L76
