### ISSUE TITLE
Cannot use namespace 'FrameContextProps' as a type.

### ISSUE THREAD

**Issue by seleckis** [ryanseddon/react-frame-component#201]
Typescript throws error when using `FrameContextProps` or `FrameComponentProps`.
Please check example: https://codesandbox.io/s/goofy-paper-xesyu?file=/src/App.tsx

<img width="583" alt="Screenshot 2021-12-06 at 12 54 05" src="https://user-images.githubusercontent.com/988504/144834014-0a48579e-605d-42e8-b0e2-34f37d8ef27a.png">

**Comment by alexandretrichot** [comment]
Hello, Same cause of problem for me. I used to use `@types/react-frame-component` (which works fine) but the latest version broke this behavior due to including `index.ts` in the package.

I don't really understand this choice, if anyone has an idea...

The workaround I use is to declare the types of the module in my project to override the official `declare module 'react-frame-component';`.

```ts
declare module 'react-frame-component' {
  import * as React from 'react';

  export interface FrameComponentProps extends React.IframeHTMLAttributes<HTMLIFrameElement> {
    head?: React.ReactNode | undefined;
    mountTarget?: string | undefined;
    initialContent?: string | undefined;
    contentDidMount?: (() => void) | undefined;
    contentDidUpdate?: (() => void) | undefined;
    children: React.ReactNode;
  }

  export default class FrameComponent extends React.Component<FrameComponentProps> { }

  export interface FrameContextProps {
    document?: HTMLDocument;
    window?: Window;
  }

  export const FrameContext: React.Context<FrameContextProps>;

  export const FrameContextProvider: React.Provider<FrameContextProps>;

  export const FrameContextConsumer: React.Consumer<FrameContextProps>;

  export function useFrame(): FrameContextProps;
}
```

Good day !

**Comment by ryanseddon** [comment]
This is fixed with [v5.2.1](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.2.1)

**Comment by seleckis** [comment]
@ryanseddon sorry but you haven't fixed it, you just added declaration file which just overrides types from`@types/react-frame-component` to just nothing: no types are exported and could be used then.

**Comment by ryanseddon** [comment]
Ok can you fix it?

**Comment by seleckis** [comment]
@ryanseddon here is a pull request: https://github.com/ryanseddon/react-frame-component/pull/213
