### ISSUE TITLE
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by aleemb** [ryanseddon/react-frame-component#211]
I am using the component to generate an HTML preview. Sometimes the preview has a Twitter embed, which is initially of the form:

```
<blockquote class="twitter-tweet" lang="en" key="https://twitter.com/archillect/status/1505425008667074563">
<a href="https://twitter.com/archillect/status/1505425008667074563"</a>
</blockquote>
```

The Twitter JS converts this into a Twitter embed. This means these nodes are no longer present and any modification to the HTML causes the vdom to diff changes and update the preview. I suspect it is at this point it tries to delete a missing node.

I'm not sure how to catch this exception or work around it. It causes the app to crash and screen to go blank.

**Comment by ryanseddon** [comment]
If you're using react you'd be better off leveraging [react-twitter-embed](https://www.npmjs.com/package/react-twitter-embed) or similar.
