### ISSUE TITLE
Modal Component is rendered outside of the iframe

### ISSUE THREAD

**Issue by phshy0607** [ryanseddon/react-frame-component#212]
https://stackblitz.com/edit/react-ts-anmzw2?file=index.tsx

Please check the example.

The modal is showed in outside window

**Comment by ryanseddon** [comment]
You'll need to leverage `useFrame` https://stackblitz.com/edit/react-ts-ahukmk?file=Hello.tsx

```jsx
import { useFrame } from 'react-frame-component';

const Hello = () => {
  const { document } = useFrame();
  
  // And then on the Modal element use getContainer to change where the modal renders
  return <Modal getContainer={document.body}>;
}
```

You'll also need to change how you import the css as you'll need that to inject into the iframe.
