### ISSUE TITLE
Event Listeners not working on the first render

### ISSUE THREAD

**Issue by AurelianSpodarec** [ryanseddon/react-frame-component#218]
Hi there!

So I've managed to render the Frame, I've managed to access it and manipulate the DOM and all good.

So far I always had to re-save my file where the code lives to re-inject the code with the auto re-load that React does, so I was able to make the event listeners work.

However, the issue is when the Frame first renders, the event listeners don't work, I've tried a few things and coudln't make it work.

This is part of my code:
```js
    function border(event:any) {
        const item = event.target;
        getTagName(item)
       
        if(event.type == "mouseover") {
            hoverAddBorder(item)
        } else if (event.type == "mouseout") {
            hoverRemoveBorder(item)
        }
    }

    function frameContent() {
        let frameDocument = iframeRef.current.contentWindow.document
        if(frameDocument) {
            frameDocument.addEventListener("mouseover", (event:any) => border(event));
            frameDocument.addEventListener("mouseout", (event:any) => border(event));
            frameDocument.addEventListener("click", (event:any) => selectElement(event));
        }
    }

  useEffect(() => {
        frameContent()
      }, [])

    return (
        <Frame 
            ref={iframeRef}
            className="h-full w-full"    
            initialContent={initialContent}
            onLoad={frameContent}
            loading="lazy"
            frameBorder={0}
        >
            {children}  
        </Frame>
    );
}
```

I'm not sure why the event listeners don't get attached on the first render. Id assume its because the Frame is loading but not sure how to fix this.

**Comment by AurelianSpodarec** [comment]
This here works: 

```js
import Frame, { useFrame } from 'react-frame-component';

const InnerComponent = () => {
  // Hook returns iframe's window and document instances from Frame context
  const { document, window } = useFrame();

  return null;
};

const OuterComponent = () => (
  <Frame>
    <InnerComponent />
  </Frame>
);
```
(https://github.com/ryanseddon/react-frame-component#accessing-the-iframes-window-and-document)

I feel like the docs for people like me could be slightly improved. I suppose I could pull on some changes elaborating on this a bit more for people like me, meaning not as savvy with this yet.

**Comment by ryanseddon** [comment]
Glad you figured it out. I agree the docs could be improved. I'll add an issue to track it
