### ISSUE TITLE
scss style component styles doesn't work in react-frame-component

### ISSUE THREAD

**Issue by raguct25** [ryanseddon/react-frame-component#226]
I have used scss styles in render component  whenever i render directly the styles applied properly. but i render inside the react-frame the styles doesn't apply.

```
import Frame from 'react-frame-component';

<Frame>
  <Placeholder
    name="jss-help-center-l3-white-test"
    rendering={rendering}
    renderEach={RenderTemplateComponent}
    errorComponent={PlaceholderError}
  />
</Frame>
```
with Frame output:

![image](https://user-images.githubusercontent.com/35067734/192487385-57235489-afbe-44bd-99b4-0a0b78c4c407.png)

without frame output:

![image](https://user-images.githubusercontent.com/35067734/192487695-7af18131-f59e-43cd-bfba-f234e52dce5b.png)

what I do for apply scss style.

**Comment by ryanseddon** [comment]
You need to inject the styles into the iframe, if your using a `<link>` tag then you can pass that to the head prop:

```jsx
<Frame head={<link href="/path/to/styles.css" rel="stylesheet">}>
...
</Frame>
```

Other options are to copy the link tags from the parent document into the frame  using `contentDidMount`.
