### ISSUE TITLE
Frame.js render twice with react 18.2.0

### ISSUE THREAD

**Issue by Tifayq** [ryanseddon/react-frame-component#239]
Render twice causes Frame render null.

Render 1: iframe not loaded.
componentDidMount triggered.
Render 2: iframe loaded, and get right result from `renderFrameContents()`.
componentWillUnmount triggered.
Render 3: iframe loaded, but `this._isMounted` is false, get null from `renderFrameContents()`.
componentDidMount triggered.

Frame.js Debug Code:
```
{
    key: 'render',
    value: function render() {
      var props = _extends({}, this.props, {
        srcDoc: this.props.initialContent,
        children: undefined // The iframe isn't ready so we drop children from props here. #12, #17
      });
      delete props.head;
      delete props.initialContent;
      delete props.mountTarget;
      delete props.contentDidMount;
      delete props.contentDidUpdate;
      delete props.forwardedRef;

      console.debug('render', this.state.iframeLoaded, this.state.iframeLoaded && this.renderFrameContents())

      return _react2.default.createElement(
        'iframe',
        _extends({}, props, { ref: this.setRef, onLoad: this.handleLoad }),
        this.state.iframeLoaded && this.renderFrameContents()
      );
    }
}
```

Console:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/16269184/221945829-6fe5659e-d0bd-4a29-971b-927b0e5a71a3.png">

**Comment by ryanseddon** [comment]
I'm pretty sure this is a react thing to make sure your components are concurrent ready they refer to it as [double invoking](https://legacy.reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects:~:text=Strict%20mode%20can%E2%80%99t%20automatically%20detect%20side%20effects%20for%20you%2C%20but%20it%20can%20help%20you%20spot%20them%20by%20making%20them%20a%20little%20more%20deterministic.%20This%20is%20done%20by%20intentionally%20double%2Dinvoking%20the%20following%20functions%3A).
