### ISSUE TITLE
scss module styles are not working

### ISSUE THREAD

**Issue by Ritesh560** [ryanseddon/react-frame-component#241]
Hi, thanks for this amazing component but I am getting issues while using this with my react app. Can you help me by telling what am i missing.

I am using this frame like this:-
<Frame><App/></Frame>

in App.js
we are importing scss modules like import styles from "./styles.scss" and using this in classname as styles.class.

The scss is not loading when we use this Frame tag.

Thanks in advance.

**Comment by ryanseddon** [comment]
I get this question a lot so will create an open issue to add it to the readme but in the mean time.

You'll need to leverage the `FrameContextConsumer` or the `useFrame` hook to get access to the iFrames document.

In your case it will probably be easiest to clone the style tag injected for that scss module into the head of the iframe.

See demo : https://codesandbox.io/s/inspiring-solomon-r8ido1?file=%2Fsrc%2FApp.js

```js
// Grab document instance from Frame context
const { document: doc } = useFrame();

// Only need to run this once on mount
useEffect(() => {
    // query document of parent
  const styleTag = document.head.querySelector("style");
  const frameStyles = styleTag.cloneNode(true);
  
  // doc is reference to iframe document
  doc.head.append(frameStyles);
}, []);
```

This gets reference to the iframe document using the `useFrame` hook and then querys for the first style tag, clones it and appends it to the iframe `<head />`.

**Comment by Tiffanysbear** [comment]
it is not work for css in your demo.

![image](https://user-images.githubusercontent.com/15380527/234170605-6f8deb55-725b-45ae-bec4-1f61a06d4203.png)

**Comment by wangly19** [comment]
ColorPicker is unable to display the content panel properly. 

look: 
<img width="1267" alt="image" src="https://github.com/ryanseddon/react-frame-component/assets/45115006/a0c97324-352a-4f7d-aca7-500e51c5ad34">

**Comment by ryanseddon** [comment]
Can you share the codesandbox?

**Comment by wangly19** [comment]
> 可以分享一下codesandbox吗？

OK，我认为这是antd的问题。

demo: https://stackblitz.com/edit/react-ezrpsx-qbfr8s?file=demo.tsx

**Comment by ryanseddon** [comment]
So dug into this and it seems antd popover uses rc-tooltip and when inside an iframe the css inset property isn't calculated correctly and it quickly changes to 0, 0 but then jumps to -1000vh, -1000vw.

<img width="417" alt="Screenshot 2024-04-30 at 2 50 32 pm" src="https://github.com/ryanseddon/react-frame-component/assets/143402/38fe8fab-f16b-4d55-981c-2df2f5a1ae8a">

I created a reduced test case with just rc-tooltip and it does the same thing when inside an iframe. https://stackblitz.com/edit/vitejs-vite-m1stud?file=src/App.jsx,package.json&terminal=dev

**Comment by wangly19** [comment]
> So dug into this and it seems antd popover uses rc-tooltip and when inside an iframe the css inset property isn't calculated correctly and it quickly changes to 0, 0 but then jumps to -1000vh, -1000vw.
> 
> <img alt="Screenshot 2024-04-30 at 2 50 32 pm" width="417" src="https://private-user-images.githubusercontent.com/143402/326675755-38fe8fab-f16b-4d55-981c-2df2f5a1ae8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMDc1MDksIm5iZiI6MTcyNjIwNzIwOSwicGF0aCI6Ii8xNDM0MDIvMzI2Njc1NzU1LTM4ZmU4ZmFiLWYxNmItNGQ1NS05ODFjLTJkZjJmNWExYWU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwNjAwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTQxYjZlOTU2MDhhNDU2NzY0NDkxMDM0Mjk4ZWU4MGY2MDcyNDI1ZmVjZDVhYTg0YWJkMWE2ZGVkOTBjOGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0oNgy7WACAXATp5LD0Z-FQdYsbv-JWLxCX7U3Qpayh8">
> I created a reduced test case with just rc-tooltip and it does the same thing when inside an iframe. https://stackblitz.com/edit/vitejs-vite-m1stud?file=src/App.jsx,package.json&terminal=dev

I have solved the problem.
As below: 
`
<FrameContainer
      className={classes.frame}
      initialContent={tpl}
      mountTarget="#frameRoot"
    >
      <FrameContextConsumer>
        {({ window: _window, document: _document }) => {
Object.setPrototypeOf(
            (_window as any).HTMLElement.prototype,
            HTMLDivElement.prototype
          );
return (
 props.children
)
</FrameContextConsumer>
    </FrameContainer>
`
