### ISSUE TITLE
Error in Remix app

### ISSUE THREAD

**Issue by jsgv** [ryanseddon/react-frame-component#252]
I am unable to get it to work on a Remix app. I get the following error message:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

Code:
```tsx
import Frame from "react-frame-component";

export default function Index() {
  return (
    <div>
      <p>Hello</p>
      <Frame>
        <h1>Testing</h1>
      </Frame>
    </div>
  );
}

```

Sandbox Link:
https://codesandbox.io/p/devbox/crimson-night-pydmg6?file=%2Fapp%2Froutes%2F_index.tsx

**Comment by jsgv** [comment]
So it looks like the importing of the library is weird. The `Frame` component I need is the `default` field.

```tsx
import Frame from "react-frame-component";

export default function Index() {
    console.log(Frame);

    return (
        <div>
            <p>Hello</p>
            <Frame.default>
                <h1>Testing</h1>
            </Frame.default>
        </div>
    );
}
```

### Console
![image](https://github.com/ryanseddon/react-frame-component/assets/2798097/9a2c5ba8-a1d9-4e9a-aa95-b4cf477c5ceb)

**Comment by ryanseddon** [comment]
So I think this is something weird Remix is doing with modules that have a default export. As even if I try and do:

```js
import { default as Frame } from 'react-frame-component';
```

Logging out Frame still returns all the exports?

I even tried a different component that also default exports and it's the same error? https://codesandbox.io/p/devbox/determined-cherry-srvpy3?file=/app/routes/_index.tsx:9,19

I'd reach out to remix and see what their compiler is doing to default export modules in routes.

**Comment by jsgv** [comment]
It seems you are correct about Remix doing something weird with `default` imports. I guess I will have to check with them. Thanks for the reply @ryanseddon
