### ISSUE TITLE
Context not available in child components

### ISSUE THREAD

**Issue by timjacobi** [ryanseddon/react-frame-component#29]
```JSX
var Hello = React.createClass({
  contextTypes: {
    color: React.PropTypes.string
  },
  render: function() {
    return <div>Hello {this.props.name} {this.context.color}</div>;
  }
});

var App = React.createClass({
  childContextTypes: {
    color: React.PropTypes.string
  },
  render: function(){
  	return (
    	<Frame>
      	<Hello name="World" />
      </Frame>
    );
  },
  getChildContext: function() {
    return {color: "purple"};
  }
});

ReactDOM.render(<App />, document.getElementById('container'));
```
Using this code I would expect the `div` in the frame to display *Hello World purple* but it only displays *Hello World*. Reason is that the `<Frame>` component uses `React.render` and context is not preserved across `React.render` boundaries. This especially comes into play when using react with redux.

Here is a live example:
https://jsfiddle.net/69z2wepo/27818/

**Comment by ibash** [comment]
@timjacobi you can fix that with `unstable_renderSubtreeIntoContainer` instead of `render`. `unstable_renderSubtreeIntoContainer` allows you to pass in a parent component. AFAICT it's still not documented.

https://jsfiddle.net/qaw1pnf8/
