### ISSUE TITLE
Load Css in iframe

### ISSUE THREAD

**Issue by rjeffer** [ryanseddon/react-frame-component#37]
Hello,

Is it possible to have an external css file load inside the frame component? I am currently having trouble loading into the iframe.

The frame is losing the content and styles. If I remove the frame, it works perfectly.

Can someone please help me with this? Thanks in advance.

**Comment by acousineau** [comment]
So I had the same question - turns out in a blog post that Ryan wrote, he addresses how to do this.

https://developer.zendesk.com/blog/2014/05/13/rendering-to-iframes-in-react/#what-about-css-in-the-iframe

**Comment by ryanseddon** [comment]
We've also introduced a new prop `initialContent` where you can specify `<script>` or `<style>` elements this will only render once when the component is mounted so if you don't need to keep updating the styles that would be your best option.

Check out this [demo](http://www.webpackbin.com/Vkd_EqKng) that's loading bootstrap from their CDN inside the frame. Just make sure you click run in the demo to see the results.

**Comment by jokeyrhyme** [comment]
It feels dirty, but I've been doing this:

```js
const initialContent = `<!DOCTYPE html><html><head>${document.head.innerHTML}</head><body><div></div></body></html>`;
export const Blah = () => (
  <Frame initialContent={initialContent}>
  { /* ... */ }
  </Frame>
);
```

It just copies everything in the outer document's head into the inner document.

I'm using this with a project started from https://github.com/davezuko/react-redux-starter-kit and using CSS modules. I haven't figured out a better way to preserve styles hot-loading whilst also only copying across the styles for this component. /shrug

**Comment by bewestphal** [comment]
I'm able to get updates upon re-render with this pattern

```
renderHead = () => {
    const {styleDependencies} = this.props
    return (
      <React.Fragment>
        <div dangerouslySetInnerHTML={{__html: document.head.innerHTML}} />
        {styleDependencies.map(url => <link rel="stylesheet" href={url} />)}
      </React.Fragment>
    )
  }

  render() {

    return (
      <FrameComponent
        head={this.renderHead()}
        style={{height: "100vh", width: "100vw"}}
        ref={this.handleRef}
      >
        {this.props.children}
      </FrameComponent>
    )
  }
```

**Comment by piotros** [comment]
Any updates on this issue?

**Comment by alisouran** [comment]
it works for me:

```tsx
export const IFrame = (props) => {
  const [contentRef, setContentRef] = useState<any>(null);
  const mountNode = contentRef?.contentWindow?.document?.body;
  const headNode = contentRef?.contentWindow?.document?.head;

  useEffect(() => {
    if (headNode) {
      headNode.innerHTML = document?.head?.innerHTML;
    }
  }, [headNode]);

  return (
    <iframe {...props} ref={setContentRef}>
      {mountNode && createPortal(props.children, mountNode)}
    </iframe>
  );
};
```

**Comment by ryanseddon** [comment]
@alisouran you get weird issues with that code in Firefox. If iframes were that easy in react then this library wouldn't exist.

**Comment by KamauAlex** [comment]
> It feels dirty, but I've been doing this:
> 
> ```js
> const initialContent = `<!DOCTYPE html><html><head>${document.head.innerHTML}</head><body><div></div></body></html>`;
> export const Blah = () => (
>   <Frame initialContent={initialContent}>
>   { /* ... */ }
>   </Frame>
> );
> ```
> 
> It just copies everything in the outer document's head into the inner document.
> 
> I'm using this with a project started from https://github.com/davezuko/react-redux-starter-kit and using CSS modules. I haven't figured out a better way to preserve styles hot-loading whilst also only copying across the styles for this component. /shrug

@ryanseddon  is there a better way other than this to load external css? At some point you lose the styles and you need to reload a component to get the styles

**Comment by AurelianSpodarec** [comment]
So what is the optimal way to load CSS into the `<Frame>` component?  There seems to be multiple answers here and some from many years back.

**Comment by ryanseddon** [comment]
Are you able to create a small test case showing your problem?

Right now you can load CSS a few ways

1. Via the `head` prop:

```jsx
<Frame head={<link href="https://unpkg.com/open-props" rel="stylesheet" />}></Frame>
```

This should re-render on updates: https://github.com/ryanseddon/react-frame-component/blob/94e5df92d44c6cd35859ef0522d7483a7ea3b93b/src/Frame.jsx#L115-L118

2. Via the `intialContent` prop:

```jsx
const initialContent = `<!DOCTYPE html><html><head><link href="https://unpkg.com/open-props" rel="stylesheet" /></head><body><div></div></body></html>`;
 
<Frame initialContent={initialContent}></Frame>
```

This will only happen on first render.

3. You can just add a `<link />` tag inside the frame too:

```jsx
<Frame>
  <link href="https://unpkg.com/open-props" rel="stylesheet" />
  { /* ... */ }
</Frame>
```

**Comment by BenRauzi** [comment]
@ryanseddon Is there a way to load CSS Modules (e.g. using test.module.css and `styles={styles.cssName}`) within react-frame-component?

**Comment by Ritesh560** [comment]
> 
I'm having same issue using this library with scss module.
Have you found any solution for this?

**Comment by BenRauzi** [comment]
@Ritesh560 I found the way was to look at my build output. In this case I was using a React CRA app which output from build a `static/css/main.css` and `statis/css/content.css`. I referenced this in the `initialContent`

```jsx
const initialContent = () => {
    return `<!DOCTYPE html>
      <html>
        <head>
          <link href="${chrome?.runtime?.getURL("/static/css/main.css")}" rel="stylesheet" />
          <link href="${chrome?.runtime?.getURL("/static/css/content.css")}" rel="stylesheet" />
        </head>
        <body>
          <div id="page" class="page"></div>
        </body>
      </html>`
}
```

```jsx
  <Frame initialContent={initialContent()}>
       <div className={"extension-context"}>
            <FrameProvider>
                 <App />
            </FrameProvider>
      </div>
</Frame>
```

This allowed my SCSS modules to work, then I used this method to provide styles for Material UI as well.

```jsx
const memoizedCreateCacheWithContainer = weakMemoize(container => {
  let newCache = createCache({ container, key: "muis" });
  return newCache;
});

export const FrameProvider = ({ children }) => (
  <FrameContextConsumer>
    {({ document }) => {
      return (
        <CacheProvider value={memoizedCreateCacheWithContainer(document.head)}>
          {children}
        </CacheProvider>
      );
    }}
  </FrameContextConsumer>
);

```
