### ISSUE TITLE
Empty previous body content

### ISSUE THREAD

**Issue by gunzip** [ryanseddon/react-frame-component#39]
I'm trying to use a scoped iframe for a react widget. It looks like calling ReactDOM.render and mounting to document.body "destroys" (empty) the whole page (body) existing content:

```
    ReactDOM.render(
      <Frame>
          <Root history={history} routes={routes} store={store} />
      </Frame>,
      document.body)
```

I would like to preserve the previous content. Is it possible ?

**Comment by ryanseddon** [comment]
You shouldn't render to `document.body` this could be the reason it's rerendering the entire tree as you may have a browser plugin that injects foreign markup that confuses react.

If that's not the case can you post a small test case use something like http://www.webpackbin.com/.

**Comment by gunzip** [comment]
I have double checked the issued, it's due to bad markup (unclosed tags) inside the cointainer page. Feel free to close this task and thank you for your work.
