### ISSUE TITLE
Components in the iFrame refers to the wrong window object

### ISSUE THREAD

**Issue by micky2be** [ryanseddon/react-frame-component#40]
When using react-frame-component I noticed that when I wrote my own listeners on the window object for component in the iFrame it will unfortunately refers to the parent window.

This can be very problematic when using third party components.

**Comment by martijnvermaat** [comment]
Not sure what you're doing exactly, but a strategy like this help you?

react-bootstrap/react-bootstrap#463

**Comment by ryanseddon** [comment]
This is a tough one for 3rd party components but for your own you can do as @martijnvermaat suggested and use `ownerDocument` to get the right context.

**Comment by darthtrevino** [comment]
The Document and Window are now passed down available as context values. I think this problem is solved.
