### ISSUE TITLE
Error when loading full page's HTML

### ISSUE THREAD

**Issue by raphaelkross** [ryanseddon/react-frame-component#43]
Hi!

I'm trying to link a iframe and inject a component inside it - all good. The main problem is that script tags with src in the document make the following error to be returned: **Invariant Violation: _registerComponent(...): Target container is not a DOM element.**

Inline scripts are apparently working, but an example of line that break things is:

`<script type='text/javascript' src='http://localhost:8888/matty/wp-includes/js/jquery/jquery.js?ver=1.12.3'></script>`

Anyone have any idea of why the error and if there's a workaround?!

Kindly,
Rafael Angeline

**Comment by ryanseddon** [comment]
Could you create a reduced test case please. http://www.webpackbin.com/ makes it easy to pull in npm modules.

**Comment by raphaelkross** [comment]
Hi @ryanseddon 

I tried to build an test case in the webpackbin, but weirdly (not so weirdly in the end) - it worked properly. I then checked my code and instead hard coding the HTML inside a string, I used the whatwg-fetch module to get the HTML source async (after a small adjust at CORS, since it were in another port than my app) - everything worked properly.

That's perfect! Thank you so much for react-frame, it's awesome and works exactly the way I need!

Kudos! 👍

**Comment by serraventura** [comment]
Hey @ryanseddon,

did you use "initialContent" property to load your full page? I need to do something similar.

**Comment by ryanseddon** [comment]
@serraventura can you create a test case of what you're trying to do.

**Comment by serraventura** [comment]
Ops... The msg was supposed to go to @raphaelkross if he could share some code.

But, off course you can help me :)

I'll try to build something on webpackbin but I'll leave some part of the code, the general idea.

I'm getting the content from the URL of the template.

```
function getTemplateContent(url) {
    let p = new Promise( (resolve, reject) => fetch(url).then( res => res.text() ).then(data => resolve(data)).catch(err => reject(err)));
    return p;
}
```

And trying to add it to the <Frame> component:

```
import * as React from "react";
import Frame from "react-frame-component";

export default class LiveTemplate extends React.Component {

    constructor(props) {
        super(props);
    }

    contentDidMount() {
        console.log('contentDidMount');
    }

    render() {
        return (<div><Frame initialContent={this.props.selectedTemplateContent}></Frame></div>);
    };

}
```

**Comment by serraventura** [comment]
**this.props.selectedTemplateContent** has the content of the URL, which is a HTML.

**Comment by serraventura** [comment]
@ryanseddon not able to recreate the issue with webpackbin (the tool is amazing though).
https://github.com/christianalfoni/webpack-bin/issues/201

It seems that something in my vendor.js is breaking with iframe.

Do you know any other online tool like webpackbin where I can have multiple files ?

**Comment by ryanseddon** [comment]
@serraventura what's `this.props.selectedTemplateContent` when it's passed to `<Frame />`? From your code above it looks like you're passing a promise object and not a string to `initialContent`

**Comment by serraventura** [comment]
This is the other bit I didn't share. The promise is resolved and I can say for sure this is a string on **selectedTemplateContent**.

```
getTemplateContent(URL).then(templateContent => {

                        dispatch({
                            type: SELECT_TEMPLATE,
                            payload: {
                                selectedTemplateContent: templateContent,
                            }
                        });

                        dispatch( openLiveTemplate(true) );

                        dispatch( loading(false) );

                    }).catch(err => {
                        dispatch( loading(false) );
                        console.error('Action getTemplateContent() Error: ', err);
                    });
```

**Comment by serraventura** [comment]
The HTML example I'm trying to load.

```
<!doctype html>
<html>
<head>
	<link rel="stylesheet" href="styles/main.css" media="all">
</head>
<body ng-app="myFanPageApp" class="myfp">
<article class="myfp__container">
<header class="myfp__header"></header>
<div ng-controller="WebContentCtrl" class="myfp__main" ng-view=""></div>
<footer class="myfp__footer"></footer>
</article>
<script src="vendor.js"></script>
<script src="scripts.js"></script>
<script src="config.js"></script>
</body>
</html>

```
