### ISSUE TITLE
iFrame src

### ISSUE THREAD

**Issue by richard-flosi** [ryanseddon/react-frame-component#44]
Hello,

I've been playing with your component recently as a way to load a legacy app alongside a new greenfield app. Without setting the `src` attribute on the iFrame, the iFrame doesn't have the correct window context which leads to relative resource requests like ajax requests to be made to the wrong url and issues with cookies being passed along, etc. I figured out how to set the `src` using the `contentDidMount` hook, but once I set that, then everything about this component gets blown away and I'm left with just a regular iFrame again.

Just wondering if using the `src` attribute is something you've used and if you have an suggestions or feedback regarding it.

Thanks!

**Comment by ryanseddon** [comment]
Are you passing a url to the src? This component is more about constructing an iFrame on the fly and injecting the DOM into it, it won't handle passing a url to the src prop.

**Comment by grrowl** [comment]
Couldn't you just use a regular `<iframe onLoad={ this.handleFrameLoaded } src="/frame.html" />` ?
