### ISSUE TITLE
In React 15.2 you get warning errors for unknown props

### ISSUE THREAD

**Issue by allanpope** [ryanseddon/react-frame-component#45]
Warning: Unknown props `styleName`, `initialContent`, `contentDidMount`, `contentDidUpdate` on <iframe> tag. Remove these props from the element

**Comment by ryanseddon** [comment]
Thanks will take a look at this soon, if you're up for a PR that would be helpful.

**Comment by allanpope** [comment]
No problem, Im still new to React but il take a crack at it sometime this week and see if I can fix it.

**Comment by ryanseddon** [comment]
Ace let me know if you need any help.

**Comment by allanpope** [comment]
Had a play around. The issue/warning seems to be when you create the iframe React element and pass it the props that were set on the parent Frame. I'm not sure on why the warning is triggered though, as it seems like your only passing through the props that the iframe needs.

```
render: function() {
    // The iframe isn't ready so we drop children from props here. #12, #17
    return React.createElement('iframe', assign({}, this.props, {children: undefined}));
}
```

```
getDefaultProps: function() {
    return {
      initialContent: '<!DOCTYPE html><html><head></head><body><div></div></body></html>',
      contentDidMount: function() {},
      contentDidUpdate: function() {}
    };
}
```

**Comment by ryanseddon** [comment]
`this.props` contains all props on `<Frame>` so we'll need a whitelist of allowed props `style`, `className` and anything else people may need that is a valid html attribute.

**Comment by allanpope** [comment]
As I understand it, you should set default props / have a whitelist of the props that your component will consume and you should remove props that your component does not need, rather than just inheriting everything.

Looking at the code the <iframe> tag needs all the props passed to it via `this.props`. So like you say above comment, we need a whitelist. I kind of thought `getDefaultProps` would do that job as you specifying that you need these props and here are the default values if they are not passed in.

Ive tried a couple other ideas I had but I'm stumped on this at the moment. I might be missing something obvious tho as I'm pretty new to React.

**Comment by urara** [comment]
Hello

I encountered the same warning.
It seems unnecessary that the props(initialContent, contentDidMount, contentDidUpdate) when iframe created.(Is my understanding incorrect?)

take a look at this commit https://github.com/urara/react-frame-component/commit/b01976d55cce6ed17ad1d87f8be0a8111520da95
I remove the props from iframe in render()
I confirmed that there is no error on console In React 15.2

This commit refers https://facebook.github.io/react/warnings/unknown-prop.html

**Comment by pcperini** [comment]
@urara could you open a pull request for this fix?

**Comment by ryanseddon** [comment]
Published v0.6.2

**Comment by NameFILIP** [comment]
I'm still getting a warning about the `mountTarget` on iframe

**Comment by ryanseddon** [comment]
Oops I think we missed that prop, wanna do a PR to make sure we have all
the props.

**Comment by NameFILIP** [comment]
Should this issue be reopen so that it won't be forgotten?

**Comment by ouraosm** [comment]
I think all we have to do is remove `head` and `mountTarget` from `props` variable.
We don't get warning as long as we use standard attributes(ex. `src`, `width`, `height` ...)
(cf: https://facebook.github.io/react/docs/tags-and-attributes.html)

**Comment by urara** [comment]
I think all we have to do is remove head and mountTarget from props variable.
We don't get warning as long as we use standard attributes(ex. src, width, height ...)
(cf: https://facebook.github.io/react/docs/tags-and-attributes.html)
