### ISSUE TITLE
const in render() can break browser builds

### ISSUE THREAD

**Issue by STRML** [ryanseddon/react-frame-component#47]
Older browsers don't support this - to get this module working requires a hacky pass through babel.

https://github.com/ryanseddon/react-frame-component/blob/7d36856268d5fa71b5128c01f3419455f284e958/index.js#L47

**Comment by ryanseddon** [comment]
yikes that will teach me for getting so used to transpiling.

**Comment by ryanseddon** [comment]
@STRML that's fixed in v0.6.4
