### ISSUE TITLE
How to hot reload CSS?

### ISSUE THREAD

**Issue by madshargreave** [ryanseddon/react-frame-component#52]
Hi

I am developing a third-party JS widget inside a react frame, but have not been able to get hot module reload working with CSS (JS works fine)

My approach is to include a link element inside the frame which references the asset URL for the CSS file through the webpack asset plugin (which gives you the name of the dynamically generated css files)

I have not been able to get this to work

Any ideas?

**Comment by ryanseddon** [comment]
Can you show me some code hard to help you without an example project

**Comment by srigi** [comment]
I'm facing the same problem - using Webpack & css-loader to style my widget. I load the widget to the page same as google-analytics, by small snippet of JS that inserts a script file into DOM. Like:

```
a = d.createElement(s);
a.async = 1;
a.src = 'http://localhost:5001/build/app.js';
m = d.getElementsByTagName(s)[0];
m.parentNode.insertBefore(a, m);
```

That `app.js` is a react application build with Webpack with css-loader. All styles of the react-app are applied to host page, not iframe. I understand that this component shouldn't solve this, but @ryanseddon can you for example tell how you style your zendesk widget?

**Comment by srigi** [comment]
OK, I found solution to style and to my surprise even hot-reloading is working :D

Code to inject styles is like in docs:

```
<Frame
  head={
    <link type="text/css" rel="stylesheet" href="http://localhost:5001/build/app.css" />
  }
  initialContent={`<!doctype html>
                  <html lang="en">
                  <head></head>
                  <body>
                    <div id="appRoot"></div>
                  </body>
                  </html>`}
  mountTarget="#appRoot"

>
  <TodosApp />
</Frame>
```

Note how stylesheet is pointing to webpack-dev-server (like in my previous comment). Now all you have to do is properly configure Webpack:

```
import ExtractTextPlugin from 'extract-text-webpack-plugin';

const webpackConfig = {
  hotPort: HOT_RELOAD_PORT,

  entry: {
    app: IS_PRODUCTION ? [
      path.join(SRC_DIR, 'client/index.jsx'),
    ] : [
      `webpack-hot-middleware/client?path=http://www.quantop-tracker.dev:${HOT_RELOAD_PORT}/__webpack_hmr`,
      path.join(SRC_DIR, 'client/index.jsx'),
    ],
  },

  module: {
    loaders: [
      {
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader'),
        test: /\.(css)$/,
      },

      ...
    ],
  },

  plugins: (() => {
    const plugins = [
      // default plugins for both envs
    ];

    if (IS_PRODUCTION) {
      plugins.push(
        new ExtractTextPlugin('app-[hash].css', {...}),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.UglifyJsPlugin({...}),
        new webpack.SourceMapDevToolPlugin({...}),
      );
    } else {
      plugins.push(
        new ExtractTextPlugin('app.css', {
          allChunks: true,
        }),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
      );
    }

    return plugins;
  })(),
}
```

We're using `ExtractTextPlugin` in both environments (dev & build) and that's the trick. Works like a charm.

**Comment by ryanseddon** [comment]
nice thanks @srigi, closing this now.
