### ISSUE TITLE
Difficult to style iframed content

### ISSUE THREAD

**Issue by darthtrevino** [ryanseddon/react-frame-component#54]
The iframe content is rendered into a div within a div within the body of the element: `body -> div -> div -> [child nodes]`. This is a PITA to write CSS for.

**Comment by ryanseddon** [comment]
Just use class names.

**Comment by darthtrevino** [comment]
I would love to, but the component is injecting a div without a classname here (https://github.com/ryanseddon/react-frame-component/blob/master/index.js#L67). If this div a class-name in addition to the `initialContent` injection you suggested that would be sufficient for my use case.

**Comment by ryanseddon** [comment]
But you can just style your content regardless of the wrapper elements around your conent.

```jsx
<Frame>
  <div className='your-class-here' />
</Frame>
```

I'm not sure what the other elements are doing to affect your styling?

**Comment by darthtrevino** [comment]
So by default, the DOM looks like this in my scenario:

![screen shot 2016-09-28 at 10 31 32 pm](https://cloud.githubusercontent.com/assets/113544/18942728/b22287d4-85cf-11e6-9f68-8aaaef661677.png)

The `div` element with `data-reactid=".1"` is the automatically injected `div`. 

This is how I want the DOM to look:
![screen shot 2016-09-28 at 10 33 27 pm](https://cloud.githubusercontent.com/assets/113544/18942801/4a6c2eaa-85d0-11e6-980d-7459a406a7f8.png)

I'm using flex-boxes so that my widget will grow to use all of the available space it's given. Using `initialContent`, I can style the body and outer div to be flex boxes, but then having a div in block display mode between flex-boxes breaks that.

**Comment by ryanseddon** [comment]
Ah flexbox gotcha, just reopened your PR.
