### ISSUE TITLE
Add beforeRender hook with iframe document passed

### ISSUE THREAD

**Issue by srigi** [ryanseddon/react-frame-component#55]
Hi, I really like the idea of [styletron](https://github.com/rtsao/styletron). This thing allows really nice concept of components' styles. However this also needs a raw `<style>` element to be mounted to the DOM before rendering. With this components this cannot be achieved now - `style` element must be attached to the `iframe`'s DOM, not the host page.

But by inserting this

```js
this.props.beforeRender(doc);
```

before [this line](https://github.com/ryanseddon/react-frame-component/blob/beba263c7c4b27ed946b8aff5b84f3caf40b1a1f/index.js#L81) will do the trick. That way I will be able to do:

```jsx
const styleSheet = document.createElement('style');
const styletron = new Styletron(styleSheet);

<Frame
  beforeRender={(doc) => {  // exposing iframe document
    doc.head.appendChild(styleSheet);
  }}
>
  <StyletronProvider styletron={styletron}>
    <MyApp />
  </StyletronProvider>
</Frame>
```

Are you willing to accept PR?

**Comment by darthtrevino** [comment]
I think you'll be able to do this using the new context values for `document` and `window`. Check the example for how to access those

**Comment by srigi** [comment]
Thanks, will check it out.
