### ISSUE TITLE
Using react-frame-component in firefox is generating an browser history entry

### ISSUE THREAD

**Issue by shashankcs090** [ryanseddon/react-frame-component#57]
I am trying to use react-frame-componet@0.6.5 in firefox to render and iframe. 
But in firefox it is pushing it an state entry into history, which is giving an unintentional behavior were if we press the back button(ie trigger history.back()) the contents inside the iframe are getting vanished. Screenshot with firefox is attached below
Usage:
ReactDOM.render(<Frame>Hello world</Frame>, div);

![image](https://cloud.githubusercontent.com/assets/3319024/22700801/c433674e-ed81-11e6-8648-cb72665a1d8c.png)

**Note:** This problem also exists in latest version....... (ie) 1.0.0

**Comment by fredrikekelund** [comment]
Seeing the same problem, but only when using `hashHistory` with react-router@3.0.3 (not when using the HTML5 push state mode of `browserHistory`)

**Comment by fredrikekelund** [comment]
Submitted a PR #66 to address this
