### ISSUE TITLE
v1.0.0 does not work with Firefox anymore

### ISSUE THREAD

**Issue by slybridges** [ryanseddon/react-frame-component#58]
Hi,

After trying to upgrade to v1.0.0, I noticed that the iframe doesn't load any content anymore with Firefox.

To reproduce, a simple `<Frame><h1>Hello</h1></Frame>` won't show on Firefox. Inspecting with Dev Tools shows that the iframe is created but with an empty head and body.

Also, the demo website is using an old version of this component (v0.3.4 i believe) and it took me a while to understand why the demo was working on Firefox and not my local example :)

**Comment by slybridges** [comment]
Forgot to mention: tests were done on Firefox v51.0.1 under Ubuntu 16.04

**Comment by darthtrevino** [comment]
I've noticed this too, I'll take a look at it

**Comment by darthtrevino** [comment]
At this point in the code, doc.readyState is 'uninitialized'
https://github.com/ryanseddon/react-frame-component/blob/master/src/Frame.jsx#L92

**Comment by darthtrevino** [comment]
The issue ended up being that at this point: https://github.com/ryanseddon/react-frame-component/blob/master/src/Frame.jsx#L121 renderFrameContents() is being invoked without the correct `this` context.

**Comment by slybridges** [comment]
The fix solved the issue on my end.
Thanks for the super quick fix @darthtrevino and release @ryanseddon !
