### ISSUE TITLE
Script elements are not evaluated

### ISSUE THREAD

**Issue by stiang** [ryanseddon/react-frame-component#6]
Is there any reason why something like the following shouldn’t work? The problem is that the script element is never evaluated (at least not in a way that makes the alert pop up in the browser’s top frame).

```jsx
var Frame = require('./frame');

module.exports = PreviewArea = React.createClass({
  render: function() {
    return (
      <div id="preview">
        <Frame>
          <div>
            <script>
              alert('hi');
            </script>
          </div>
        </Frame>
      </div>
    );
  }
});
```

I’m trying to convert an ad editor to React/iframe, where the content of the iframe will contain both script and style blocks. Styles work perfectly, and script elements appear correctly in the DOM, but they are just never evaluated. Do you know if this is an inherent limitation with using iframes in this way or an issue that is particular to this component (or the combination of "the React way" and iframes)?

**Comment by ryanseddon** [comment]
Closing this issue.
