### ISSUE TITLE
How to access the iframe document from within it?

### ISSUE THREAD

**Issue by viksit** [ryanseddon/react-frame-component#61]
Thanks for this plugin - great work.

When I refer to document from within `MyComponent` which is rendered like this,

```
<Frame>
  <MyComponent/>
</Frame>
```

`document` ends up referring to the main page that contains `<Frame>`. How do I access the internal document?

**Comment by ryanseddon** [comment]
Good question! This was actually added in the 1.0.0 release but it seems we failed to add it to the documentation. 

You can access the iframes `document` and `window` properties via `context`.

So within `MyComponent` you can access it via `this.context.document`.

@darthtrevino reckon you could do a PR to update the readme to mention the `DocumentContext` component anf its purpose.

**Comment by darthtrevino** [comment]
Sure, I'll put something together this week

**Comment by viksit** [comment]
Sounds great, will try it out thanks!

**Comment by viksit** [comment]
@ryanseddon @darthtrevino any ideas?

**Comment by darthtrevino** [comment]
The document and window are available as context variables in the iframe
subtree. The docs need to be updated, but that is already in place

**Comment by viksit** [comment]
@darthtrevino ah hmm. if you take a look at the code I posted right above - it doesn't work as described by @ryanseddon earlier. Is there something I'm missing / extra config option I need?

**Comment by darthtrevino** [comment]
I'm building a fence at the moment. I'll look at it in a few hours

**Comment by darthtrevino** [comment]
I don't see you setting the contextTypes map in your component. See the
react docs here: https://facebook.github.io/react/docs/context.html

**Comment by viksit** [comment]
I'm not, thats right. I just added it, and now this.context contains what I passed in (aka, the color purple as per that tutorial you linked to), but not the `document` and `window` objects. Do you mean I have to set this manually?

**Comment by darthtrevino** [comment]
Yes, you need to add entries for the window and document
