### ISSUE TITLE
Setting for the className of the wrapper div

### ISSUE THREAD

**Issue by overtune** [ryanseddon/react-frame-component#65]
I have a case when I need to be able to set the className of the "wrapper div".
Now the class "frame-content" is hard coded in.

I have fixed this setting in a fork, so if you're interested I can do a pull-request with the changes.
Is that ok?

**Comment by ryanseddon** [comment]
Seems like a fairly trivial thing to add, what's the use case?

**Comment by overtune** [comment]
In this case I've built an admin interface for Reveal.js presentations ([http://lab.hakim.se/reveal-js](http://lab.hakim.se/reveal-js)).
I have the different slides that gets inserted into the Iframe-component for previewing. But for reveal to work the wrapper div around the slides needs to have the class "slides".

This might be a bit of an edge-case, but I think it doesn't hurt to be able to choose what className you want.
I can do a pullrequest of the changes if you like, there are not much needed to be changed:
[https://github.com/ryanseddon/react-frame-component/compare/master...overtune:master](https://github.com/ryanseddon/react-frame-component/compare/master...overtune:master)

**Comment by danakt** [comment]
It can also be used to wrap a component with tools such as styled-components
