### ISSUE TITLE
can't insert styles from frame children components

### ISSUE THREAD

**Issue by robotzhang** [ryanseddon/react-frame-component#74]
when import('index.css') in subcomponent then will insert styles to parent document <head>.
is react-frame-component can insert children components inner import styles to iframe?
the example code:
```javascript
<Frame>
  <Child />   
</Frame>
```
child.js
```javascript
import('index.css') // this will insert to parent not iframe 

```

**Comment by ryanseddon** [comment]
Can you create a test case showing the behaviour please

**Comment by robotzhang** [comment]
@ryanseddon thanks for your reply.
Because of the iframe use the same context window with parent I think append styles from components into iframe is difficult, so now my solution:

> merge styles to css file(use webpack ExtractTextPlugin) and then link the css file in Frame InitialContent

**Comment by alimoosavi15** [comment]
I know this is an old issue but another solution is to use file-loader plugin in Webpack to get the stylesheet path and add it to initialContent with a link tag.

```
import Frame from 'react-frame-component'
import styles from 'public/css/styles.iframe.css'

const initialContent = () => {
  return (
    `<!DOCTYPE html>
    <html>
      <head>
        <link href="${styles}" rel="stylesheet" />
      </head>
      <body>
        <div id="page" class="page"></div>
      </body>
    </html>`
  )
}

<Frame initialContent={initialContent()}>
    <FrameContent />
</Frame>

```
You may need to choose a specific file name for your stylesheet and add a new rule to your Webpack configuration that matches the file name:

```
module: {
      rules: [
        {
          test: /\.iframe.css$/,
          use: [
            { loader: 'file-loader' },
            { loader: 'postcss-loader' },
          ]
        },
      ]
}
```

**Comment by robotzhang** [comment]
@alimoosavi15 yes that is my solution. thanks.

**Comment by jasonhealy** [comment]
Is there a working demo of the solution by any chance? Is it possible to just just inject the styles directly into the iframe header?

**Comment by Kivylius** [comment]
I'm trying to do this too. Is there anyway to do this with node_modules CSS as well as APP files too?

**Comment by msholty-fd** [comment]
In case anyone is wanting an alternative solution, you can use `css-loader` and import a css file, then call `.toString()` on it to get the css file as a string. Then, you can load it into the `<head>` of your iframe.

The downside here is that you can only import an individual css file at a time, and can't do anything with css modules, but if the file is a sass file that imports other files, it could at least get all the necessary CSS in there for the iframe to work. It's not the best solution but it's something.

**Comment by romansky** [comment]
This works-
https://gist.github.com/sorahn/aba9e0538c0a275df4ad929b158b3e8d

**Comment by deorsi** [comment]
> This works-
> https://gist.github.com/sorahn/aba9e0538c0a275df4ad929b158b3e8d

The button should have the same look, write?
Is there a new fix I have to apply for this to work?

https://codesandbox.io/s/frosty-volhard-wx7s7

**Comment by tonychan96** [comment]
> > This works-
> > https://gist.github.com/sorahn/aba9e0538c0a275df4ad929b158b3e8d
> 
> The button should have the same look, wright?
> Is there a new fix I have to apply for this to work?
> 
> https://codesandbox.io/s/frosty-volhard-wx7s7

did you ever figure this one out?

**Comment by palashkaria** [comment]
@tonychandesign check this out, might help: not sure where the method is originally from, I just happened to find this

https://github.com/marchetti554/react-blog/blob/a6cf946904b5af4f14d8478481ec3db07db1481c/docs/src/modules/components/DemoSandboxed.js

**Comment by JohannBlake** [comment]
I notice that the iframe's body has a margin set to 8. Is it possible to change this so that it gets set to zero?

**Comment by 318097** [comment]
Hey, any update on this? Any workable solution?  `mini-css-extract-plugin` helps in bundling all the CSS from project, but it does not load the CSS from external libraries.

**Comment by sakib412** [comment]
Can I load css from any installed packages?
