### ISSUE TITLE
Allow integration with existing iFrames

### ISSUE THREAD

**Issue by aschmoe** [ryanseddon/react-frame-component#83]
I've just done some testing and just by passing a ref to an existing iframe document the `<Frame />` component can just use `this.props.document` to handle the output of non-react-controlled iframes.

I can take a pass at a PR, but figured I would get your reaction first.

Basically the only REAL point of change is

```
  getDoc() {
    return this.props.document ||   ReactDOM.findDOMNode(this).contentDocument; // eslint-disable-line;
  }
```

Though it would probably be wise to allow additional options to control what 

- `<Frame />` outputs
- optional `initialContent`

Maybe a HOC would be the best way to merge the functionality for different use cases, though seems like just adding a few prop options would certainly be easier.

Let me know

**Comment by ryanseddon** [comment]
What's the use-case for this? Do you have an example showing what you mean?

**Comment by aschmoe** [comment]
@ryanseddon in my particular case I'm interacting with the Shopify [embedded app SDK modal](https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk/methods#shopifyapp-modal-open-init-fn).  So essentially you can access a ref to the iframe, but the creation of the iframe itself is outside the abilities of the app.

I think its reasonable to assume there are other situations where apps cannot init the iframe, but could benefit from the iframe management scheme you have set up here.

**Comment by ryanseddon** [comment]
interested to see a pr but wouldn't this still render an iframe that isn't used when redirecting the doc to another iframe reference?

**Comment by ryanseddon** [comment]
interested to see a pr but wouldn't this still render an iframe that isn't used when redirecting the doc to another iframe reference?

**Comment by aschmoe** [comment]
@ryanseddon maybe https://github.com/ryanseddon/react-frame-component/pull/84 would give you a better idea of what I'm talking about.

**Comment by aschmoe** [comment]
Removed a prop that was useless in retrospect.
