### ISSUE TITLE
Blog post link is broken

### ISSUE THREAD

**Issue by IanVS** [ryanseddon/react-frame-component#86]
It looks like the link redirects to the homepage of the zendesk developer blog.

**Comment by ryanseddon** [comment]
Yeah thanks I believe this is being fixed soon, will update once it has been migrated.

**Comment by yadounis** [comment]
@ryanseddon Can you please at least send us a temporary link ? I'm trying to use this and I need more documentation.

**Comment by timmfin** [comment]
Any update? I was trying to google around and still had no luck finding the original blog post.

**Comment by efjacobson** [comment]
You can find it on the wayback machine: https://web.archive.org/web/20140523003531/http://developer.zendesk.com:80/blog/2014/05/13/rendering-to-iframes-in-react/

**Comment by ryanseddon** [comment]
It'll be republished here https://medium.com/@rseddon_16685/6236bafc7e86 just waiting on approval.

**Comment by IanVS** [comment]
Thanks!

**Comment by IanVS** [comment]
Actually, I'll leave this open until the readme is updated, because that link is still pointing to the old one.
