### ISSUE TITLE
Adjust height of iframe based on the height of content inside

### ISSUE THREAD

**Issue by mukeshsoni** [ryanseddon/react-frame-component#91]
As the content inside the iframe keeps changing, i want the height of the iframe to adjust accordingly. Looks like there is no way to do it with css alone. I need to set the height of the iframe in javascript on component updates.

I tried the following approach - 

```
<Frame
    {...propsToFrame}
>
   <Resizer />
    <MyContent />
</Frame>

class Resizer extends React.Component {
    static contextTypes = {
        window: PropTypes.any,
        document: PropTypes.any
    }

    adjustHeight = () => {
        if (this.context && this.context.document) {
             // set the frame height to this.context.document.body.scrollHeight
             // but how do i get access to the iframe DOM element
        }
    }

    constructor(props, context) {
        super(props, context)
    }

    componentDidMount() {
        this.adjustHeight()
    }

    componentDidUpdate() {
        this.adjustHeight()
    }

    render() {
        return null
    }
}
```

I am not able to figure out how to get hold of the iframe DOM element. I tried passing a `ref` prop to the `Frame` element, but am not able to reach the DOM `iframe` element.

**Comment by mukeshsoni** [comment]
I am using the below solution for now - 

```
class MyComp extends React.Component {
  iframeRef: null
  adjustHeight = () => {
    const iframeDOMNode = ReactDOM.findDOMNode(this.iframeRef)
    iframeDOMNode.height = iframeDOMNode.contentWindow.document.body.scrollHeight || 'auto'
  }
  onMount() {
    setTimeout(this.adjustHeight, 200)
  }

  onUpdate() {
    this.adjustHeight()
  }

  render() {
    return <Frame
                    ref={node => this.iframeRef = node}
                    contentDidMount={this.onMount}
                    contentDidUpdate={this.onUpdate}
                    {...otherProps}
                  >
                       <IframeContentStuff />
                   </Frame>
  }
}
```

It works but not without the 200ms delay in `onMount`. Also, it doesn't work if there are more than one `Frame` components in the window. The ref always seems to point to the first one.

**Comment by bondarewicz** [comment]
@mukeshsoni I'm currently using `setInterval` to watch the height of the `Frame` content as mine changes depending on user collapse/expand clicks - definitely not ideal solution either...

@ryanseddon would you be able to expand on below from README:  

```
contentDidMount and contentDidUpdate

... calls are sometimes triggered after the lifecycle of the parent component, 
so these callbacks provide a hook to know when the frame contents are mounted and updated
```

- when is the `contentDidUpdate` actually fired? 
- can you think of anything we could rely on for the purpose of adjusting the height beside `contentDidUpdate`?

**Comment by bondarewicz** [comment]
@mukeshsoni perhaps [Recursive setTimeout](https://javascript.info/settimeout-setinterval#recursive-settimeout) might be better fit?

**Comment by mukeshsoni** [comment]
@bondarewicz That is what i ended up doing. I just cancel the last setTimeout on componentWillUnmount

```
        adjustIframeHeight = () => {
            setTimeout(() => {
                const iframeDOMNode = ReactDOM.findDOMNode(this.iframeRef)

                if (
                    iframeDOMNode &&
                    iframeDOMNode.contentWindow &&
                    iframeDOMNode.contentWindow.document &&
                    iframeDOMNode.contentWindow.document.body &&
                    iframeDOMNode.height !==
                        iframeDOMNode.contentWindow.document.body.scrollHeight
                ) {
                    iframeDOMNode.height = iframeDOMNode.contentWindow.document
                        .body.scrollHeight
                        ? iframeDOMNode.contentWindow.document.body
                              .scrollHeight + 'px'
                        : 'auto'
                }

                this.timeoutToken = setTimeout(this.adjustIframeHeight, 500)
            }, 200)
        }
```

**Comment by ryanseddon** [comment]
> when is the contentDidUpdate actually fired?

@bondarewicz it should fire every time the frame contents are changed.

As @mukeshsoni having some sort of recursive setTimeout might be your best option.

**Comment by binarykitchen** [comment]
@mukeshsoni think there are too many setTimeout fns ... why not use `setInterval` instead?

**Comment by dmolina101** [comment]
@jagmitg the content of your iframe is in the same domain? if not you can not get that sizes

**Comment by jagmitg** [comment]
@dmolina101 yes - all the content is generated on the fly on the domain itself.

I can access the node `this.myRef.current.node`  and on the render function, on the iframe itself, i am using the ref callback `ref={this.myRef}`.

I am calling this on `componentDidMount()` not on the iframe itself.

**Comment by glebdv** [comment]
if you're on your own domain, you can try using
```
<iframe src="..."  onLoad=function() {
    //trigger method that you want to use to get height i.e:
    		var iframe = document.getElementById('iframeController');
		if(iframe) {
			iframe.height = iframe.contentWindow.document.body.scrollHeight + "px";			
		}
}>
```

**Comment by twig-openlearning** [comment]
also throwing my +1 behind having issues with detecting size changes

**Comment by kmaid** [comment]
+1

**Comment by kmaid** [comment]
`onLoad={(event: React.SyntheticEvent<HTMLIFrameElement>) => {
        if (
          event.currentTarget &&
          event.currentTarget.contentWindow &&
          event.currentTarget.contentWindow.document.body.scrollHeight !== 0
        ) {
          setHeight(event.currentTarget.contentWindow.document.body.scrollHeight);
        }
      }}`

**Comment by kmaid** [comment]
I managed to get something working. I ended up wrapping the frame into another component and using the lifecycle methods of that. Here is my code good luck :)

```typescript 
interface IProps {
  children: React.ReactNode;
}

interface IFrame {
  node: HTMLIFrameElement;
}
export const HeightChangingFrame: React.FunctionComponent<IProps> = ({
  children
}) => {
  const [height, setHeight] = useState(500);
  const iframeRef: React.RefObject<IFrame> = React.createRef();
  const handleResize = (iframe: React.RefObject<IFrame>) => {
    if (
      iframe.current &&
      iframe.current.node.contentDocument &&
      iframe.current.node.contentDocument.body.scrollHeight !== 0
    ) {
      setHeight(iframe.current.node.contentDocument.body.scrollHeight);
    }
  };
  useEffect(() => handleResize(iframeRef), [children]);
  return (
      <Frame
        ref={iframeRef}
        onLoad={() => handleResize(iframeRef)}
      >{children}</Frame>
  );
};
```

**Comment by yrodrigez** [comment]
This works for me :)
```
adjustHeight = () => {
		const iframeDOMNode = ReactDOM.findDOMNode(this.node)
		iframeDOMNode.onload = () => {
			iframeDOMNode.height = iframeDOMNode.contentWindow.document.body.scrollHeight || 'auto'
		}
	}

	componentDidMount () {
		this.adjustHeight()
	}

	componentDidUpdate () {
		this.adjustHeight()
	}

	render () {
		return <iframe
			ref={x => this.node = x}
			srcDoc={`<html lang="en"></html>`}
		/>
	}
```

**Comment by shawnwall** [comment]
+1

**Comment by ryanseddon** [comment]
Seems @kmaid has a pretty good solution closing as solved.

**Comment by feser** [comment]
@ryanseddon Can we handle this in the component to avoid duplication of logic?
For example, If height is not provided, render the frame according to its size.

**Comment by cschroeter** [comment]
Small refactoring to ensure typescript won't complain

```ts
import React, { useState, useEffect, useCallback, RefObject } from "react";
import Frame from "react-frame-component";

interface FrameRef extends Frame {
  node: HTMLIFrameElement;
}

export const IFrame: React.FC = (props) => {
  const { children } = props;
  const [height, setHeight] = useState(500);
  const iframeRef = React.createRef<FrameRef>();

  const handleResize = useCallback((iframe: RefObject<FrameRef>) => {
    const height = iframe.current?.node.contentDocument?.body.scrollHeight ?? 0;
    if (height !== 0) {
      setHeight(height);
    }
  }, []);

  useEffect(() => handleResize(iframeRef), [handleResize, iframeRef]);

  return (
    <Frame
      ref={iframeRef}
      style={{
        height,
      }}
      onLoad={() => handleResize(iframeRef)}
    >
      {children}
    </Frame>
  );
};
```

**Comment by Lornz-** [comment]
@ryanseddon I tried @kmaid solution which should work as expected but not anymore. As I see on a latest change, the `onLoad` [here](https://github.com/ryanseddon/react-frame-component/blame/aa91bbe561f0eff0a6ea47599ab0aa1183994e41/src/Frame.jsx#L125) overwrites the one passed in props.
