### ISSUE TITLE
Switch to ReactDOM.createPortal?

### ISSUE THREAD

**Issue by TuckerWhitehouse** [ryanseddon/react-frame-component#92]
Have you considered using the [ReactDOM.createPortal](https://reactjs.org/docs/portals.html) api, or would you be open to a pull-request for this change?

https://gist.github.com/robertgonzales/b1966af8d2a428a8299663b92fb2fe03

**Comment by ryanseddon** [comment]
yes! just haven't had the time to do it.

Wanna create a PR?

**Comment by TuckerWhitehouse** [comment]
Opened a pr :) #93
