### ISSUE TITLE
React 16 Portals

### ISSUE THREAD

**Issue by Fer0x** [ryanseddon/react-frame-component#94]
Since Portals were introduced in React 16, are there any benefits to use `react-frame-component` over `ReactDOM.createPortal`?
For example: https://gist.github.com/robertgonzales/b1966af8d2a428a8299663b92fb2fe03

**Comment by TuckerWhitehouse** [comment]
I have an open pull request (see #92 & #93) for migrating this library to use `ReactDOM.createPortal`. I think the benefit is in not having to recreate the same boilerplate and the additional hooks a library like this provides (such as the `initalContent` and `mountTarget`).

**Comment by Prinzhorn** [comment]
I think this can be closed as https://github.com/ryanseddon/react-frame-component/pull/103 was merged ;)

**Comment by Fer0x** [comment]
Resolved in #93
