### ISSUE TITLE
Children don't run in the proper context.

### ISSUE THREAD

**Issue by vidjuheffex** [ryanseddon/react-frame-component#99]
A component inside the iframe calls document.getElementsByTagName('head)[0] grabs the parent context.

I've seen the copy it puts in context, and other workarounds. But am curious if there is any way to get the above to work and not have to worry about it from within the component.

What I'm building sometimes renders the components in an iframe and other times not, the component code needs to be generic and 'unaware' of the iframe use the correct document. Is this possible?

**Comment by viksit** [comment]
@ryanseddon would appreciate insight into this. I have the exact same problem.

**Comment by ryanseddon** [comment]
I don't think it's possible for the script to know which document context it's currently in. You need to use the `<FrameContextConsumer>` to pass that information to the children. Once you have nested children you then need to wrap those in the `<FrameContextConsumer>` or pass them as props.

Unfortunately there is no way for a generic script to call `document` and have the right one.
